'use strict';
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const DEFAULTS={
  name:'P2000 Monitor',services:['brandweer','ambulance','politie','lifeliner','knrm'],cities:[],keywords:[],
  nightMode:true,nightStart:'23:00',nightEnd:'07:00',messageMinutes:3,maxAgeMinutes:5,dateFormat:'dd-mm-yyyy',
  idleCentered:true,burnInProtection:true,burnInPixels:12,autoTextSize:true,darkLedPercent:4,vehicleHeader:true,displaySleep:false,
  speechEnabled:true,speechCities:[],speechRate:.96,speechPitch:1,speechEngine:'online',speechDeviceVolumeDay:38,speechDeviceVolumeNight:20,speechDeviceVolumeUrgent:55,
  mapEnabled:true,mapZoom:16,backgroundStyle:'black',backgroundColor:'#020506',backgroundPhotoVersion:0,backgroundPhotoDarkness:.60,backgroundPhotoFit:'cover',kioskMonitor:'primary',idleStyle:'normal',idleDimEnabled:true,idleDimStart:'21:30',idleDimEnd:'07:00',idleDimMin:.42,
  idleDimEarliest:'20:30',smartSilenceEnabled:true,smartSilenceMinutes:30,postIncidentQuietEnabled:true,postIncidentQuietSeconds:20
};
let setupProfile=null;
let settings={...DEFAULTS};
async function api(path,opts={}){const r=await fetch(path,{cache:'no-store',...opts});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`${r.status} ${r.statusText}`);return d}
function clamp(v,a,b,d){v=Number(v);return Number.isFinite(v)?Math.max(a,Math.min(b,v)):d}
function parseList(v){return [...new Set(String(v||'').split(/[\n,;]+/).map(x=>x.trim()).filter(Boolean))].slice(0,50)}
function toggleBackgroundColor(){const style=$('#backgroundStyleInput')?.value||'black',f=$('#backgroundColorField'),p=$('#backgroundPhotoField');if(f)f.style.display=style==='custom'?'':'none';if(p)p.style.display=style==='photo'?'':'none'}
function setText(sel,v){const e=$(sel);if(e)e.textContent=v??'—'}
function flash(text,kind=''){const el=$('#testStatus');el.textContent=text;el.dataset.kind=kind}
function formToSettings(){
  return {...settings,
    name:($('#nameInput').value||'P2000 Monitor').trim().slice(0,30),
    services:$$('[data-service]').filter(x=>x.checked).map(x=>x.dataset.service),cities:[],keywords:[],
    messageMinutes:clamp($('#messageMinutesInput').value,.25,15,3),maxAgeMinutes:clamp($('#maxAgeMinutesInput').value,.25,30,5),
    vehicleHeader:$('#vehicleHeaderInput').checked,mapEnabled:$('#mapEnabledInput').checked,burnInProtection:$('#burnInProtectionInput').checked,
    speechEnabled:$('#speechEnabledInput').checked,speechEngine:'online',speechCities:parseList($('#speechCitiesInput').value),
    speechRate:clamp($('#speechRateInput').value,.65,1.25,.96),speechPitch:clamp($('#speechPitchInput').value,.75,1.3,1),
    backgroundStyle:$('#backgroundStyleInput').value||'black',backgroundColor:$('#backgroundColorInput').value||'#020506',backgroundPhotoVersion:Number(settings.backgroundPhotoVersion)||0,backgroundPhotoDarkness:clamp($('#backgroundPhotoDarknessInput')?.value,0,90,60)/100,backgroundPhotoFit:$('#backgroundPhotoFitInput')?.value||'cover',kioskMonitor:$('#kioskMonitorInput').value||'primary',displaySleep:$('#displaySleepInput').checked,nightMode:$('#nightModeInput').checked,nightStart:$('#nightStartInput').value||'23:00',nightEnd:$('#nightEndInput').value||'07:00'
  };
}
function renderSettings(s){
  settings={...DEFAULTS,...s};
  $('#nameInput').value=settings.name;$('#messageMinutesInput').value=settings.messageMinutes;$('#maxAgeMinutesInput').value=settings.maxAgeMinutes;
  $('#vehicleHeaderInput').checked=settings.vehicleHeader!==false;$('#mapEnabledInput').checked=settings.mapEnabled!==false;$('#burnInProtectionInput').checked=settings.burnInProtection!==false;
  $('#speechEnabledInput').checked=settings.speechEnabled!==false;settings.speechEngine='online';$('#speechEngineInput').value='online';$('#speechCitiesInput').value=(settings.speechCities||[]).join(', ');$('#speechRateInput').value=settings.speechRate;$('#speechPitchInput').value=settings.speechPitch;$('#backgroundStyleInput').value=settings.backgroundStyle||'black';$('#backgroundColorInput').value=settings.backgroundColor||'#020506';if($('#backgroundPhotoDarknessInput'))$('#backgroundPhotoDarknessInput').value=Math.round(clamp(settings.backgroundPhotoDarkness,0,.9,.6)*100);if($('#backgroundPhotoFitInput'))$('#backgroundPhotoFitInput').value=settings.backgroundPhotoFit||'cover';toggleBackgroundColor();backgroundPhotoInfo();
  $('#kioskMonitorInput').value=settings.kioskMonitor||'primary';$('#displaySleepInput').checked=!!settings.displaySleep;$('#nightModeInput').checked=settings.nightMode!==false;$('#nightStartInput').value=settings.nightStart||'23:00';$('#nightEndInput').value=settings.nightEnd||'07:00';
  const active=new Set(settings.services||[]);$$('[data-service]').forEach(x=>x.checked=active.has(x.dataset.service));
}
async function loadSettings(){try{const d=await api('/api/settings');renderSettings(d.settings||{})}catch(e){flash(`Instellingen laden mislukt: ${e.message}`,'error');renderSettings({})}}
async function save(){const b=$('#saveBtn');b.disabled=true;b.textContent='Opslaan…';try{const d=await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(formToSettings())});renderSettings(d.settings||formToSettings());flash('Instellingen opgeslagen ✓','ok')}catch(e){flash(`Opslaan mislukt: ${e.message}`,'error')}finally{b.disabled=false;b.textContent='Instellingen opslaan'}}
async function backgroundPhotoInfo(){const el=$('#backgroundPhotoStatus');if(!el)return;try{const d=await api('/api/background/info');if(d.exists){el.textContent=`Foto opgeslagen • ${d.type||'afbeelding'} • ${(Number(d.bytes||0)/1024/1024).toFixed(1)} MB`;settings.backgroundPhotoVersion=Number(d.version)||settings.backgroundPhotoVersion||0}else el.textContent='Nog geen achtergrondfoto opgeslagen.'}catch(e){el.textContent=`Fotostatus niet beschikbaar: ${e.message}`}}
async function uploadBackgroundPhoto(){const input=$('#backgroundPhotoInput'),file=input?.files?.[0],btn=$('#uploadBackgroundPhotoBtn');if(!file)return flash('Kies eerst een JPG, PNG of WebP.','error');if(file.size>15*1024*1024)return flash('Foto is groter dan 15 MB. Kies een kleinere afbeelding.','error');btn.disabled=true;btn.textContent='Uploaden…';try{const r=await fetch('/api/background/upload',{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream','X-File-Name':encodeURIComponent(file.name||'background')},body:file,cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`${r.status} ${r.statusText}`);settings.backgroundPhotoVersion=Number(d.version)||Date.now();$('#backgroundStyleInput').value='photo';toggleBackgroundColor();const saved=await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(formToSettings())});renderSettings(saved.settings||formToSettings());flash('Achtergrondfoto opgeslagen ✓','ok');await backgroundPhotoInfo()}catch(e){flash(`Foto opslaan mislukt: ${e.message}`,'error')}finally{btn.disabled=false;btn.textContent='Foto opslaan'}}
async function removeBackgroundPhoto(){const btn=$('#removeBackgroundPhotoBtn');btn.disabled=true;try{const d=await api('/api/background/remove',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});settings.backgroundPhotoVersion=0;if($('#backgroundStyleInput')?.value==='photo')$('#backgroundStyleInput').value='black';toggleBackgroundColor();const saved=await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(formToSettings())});renderSettings(saved.settings||formToSettings());flash(d.ok?'Achtergrondfoto verwijderd ✓':'Foto verwijderen mislukt',d.ok?'ok':'error');await backgroundPhotoInfo()}catch(e){flash(`Foto verwijderen mislukt: ${e.message}`,'error')}finally{btn.disabled=false}}
async function status(){try{const d=await api('/api/status');setText('#versionStatus',d.version);setText('#feedStatus',d.feed_status||'—');setText('#todayStatus',d.messages_today??0);setText('#lastMessageStatus',d.last_message?new Date(d.last_message).toLocaleString('nl-NL'):'nog geen');setText('#scopeStatus',d.scope);setText('#errorStatus',d.last_error||'geen');const p=$('#controlStatus');p.textContent=d.feed_status==='online'?'online':(d.feed_status||'onbekend');p.className='status-pill '+(d.feed_status==='online'?'online':'error')}catch(e){setText('#controlStatus','offline');$('#controlStatus').className='status-pill error';setText('#errorStatus',e.message)}}
async function feeds(){try{const d=await api('/api/feed-config'),urls=d.config?.primary_feed_urls||[];$('#feedList').innerHTML=urls.map((u,i)=>`<div class="feed-row"><b>${i+1}.</b> <code>${escapeHtml(u)}</code></div>`).join('')||'<div class="feed-row">Geen feeds ingesteld</div>'}catch(e){$('#feedList').textContent=e.message}}
async function reconnect(){const b=$('#reconnectBtn');b.disabled=true;b.textContent='Herverbinden…';try{await api('/api/feeds/reconnect',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});b.textContent='Aangevraagd ✓';setTimeout(status,1200)}catch{b.textContent='Mislukt'}setTimeout(()=>{b.disabled=false;b.textContent='Feeds opnieuw verbinden'},1800)}
async function displayInfo(){try{const d=await api('/api/display/info'),x=d.display||{},rows=Array.isArray(x.monitors)?x.monitors:[],sel=$('#kioskMonitorInput'),wanted=String(settings.kioskMonitor||x.selected_monitor_id||'primary');if(sel&&rows.length){sel.innerHTML=rows.map((r,i)=>`<option value="${escapeHtml(r.device||r.id||String(i+1))}">${escapeHtml(r.label||`Scherm ${i+1}`)}${Number.isFinite(r.x)&&Number.isFinite(r.y)?` • ${r.x},${r.y}`:''}</option>`).join('');if(rows.some(r=>String(r.device||r.id)===wanted))sel.value=wanted;else{const primary=rows.find(r=>r.primary);sel.value=String(primary?.device||rows[0]?.device||'primary')}settings.kioskMonitor=sel.value;const chosen=rows.find(r=>String(r.device||r.id)===sel.value);if(chosen)setText('#kioskMonitorHint',`Gekozen: ${chosen.label||sel.value} • positie ${chosen.x},${chosen.y}. Herstart de lichtkrant om naar dit scherm te verplaatsen.`)}const e=$('#displayStatus');e.textContent=x.method==='windows-monitor-power'?`${rows.length||1} scherm${rows.length===1?'':'en'} gevonden`:(x.method||'niet beschikbaar');e.className='status-pill '+(x.method?'online':'error')}catch(e){setText('#displayStatus','fout')}}
async function displayPower(mode){const id=mode==='on'?'#displayOnBtn':'#displayOffBtn',b=$(id);b.disabled=true;try{const d=await api('/api/display/power',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:mode,manual:true})});flash(d.ok?`Scherm ${mode==='on'?'aan':'uit'} via Windows ✓`:`Schermactie mislukt: ${d.error||d.status}`,d.ok?'ok':'error');displayInfo()}catch(e){flash(`Schermactie mislukt: ${e.message}`,'error')}finally{b.disabled=false}}
function inferCity(raw){const preferred=String(setupProfile?.standplaats_city||setupProfile?.standplaats||'').trim();if(preferred&&String(raw).toLowerCase().includes(preferred.toLowerCase()))return preferred;return preferred}
function inferService(raw){const s=String(raw).toUpperCase();if(/\bLIFELINER\b|(?<!\d)(?:13[- ]?991|17[- ]?992|08[- ]?993)(?!\d)/.test(s))return'lifeliner';if(/\bASS\.?\s*(?:AMBU|POL)\b|\bBR(?:AND)?\b/.test(s))return'brandweer';if(/\bPOLITIE\b/.test(s))return'politie';if(/\bA[012]\b|\bB[12]\b|\bAMBU(?:LANCE)?\b|\bMMT\b/.test(s))return'ambulance';return'brandweer'}
async function testMessage(speak){const raw=$('#testInput').value.trim();if(!raw)return flash('Vul eerst een P2000-regel in.','error');const city=inferCity(raw),service=inferService(raw);flash(speak?'Testmelding + omroep…':'Testmelding tonen…');const payload={title:raw,summary:raw,city,service,priority:/\bP\s*2\b/i.test(raw)?'P2':(/\bP\s*3\b/i.test(raw)?'P3':'P1'),speak,host_speak:false,duration_ms:60000};if(speak&&settings.speechEngine==='online'){payload.host_speak=false}try{const d=await api('/api/test-message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});flash(d.ok?'Test verzonden ✓':(d.speech_error||'Test kon niet worden uitgevoerd'),d.ok?'ok':'error')}catch(e){flash(`Test mislukt: ${e.message}`,'error')}}
async function voiceTest(){try{flash('Omroep naar lichtkrant sturen…');const place=setupProfile?.standplaats_city||setupProfile?.standplaats||'de ingestelde standplaats';const text=`Brand woning aan de Hoofdstraat in ${place}. Eerste eenheden gealarmeerd.`;const d=await api('/api/test-message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'speech-only',speech_text:text,speak:true,service:'brandweer',host_speak:false})});flash(d.ok?'Test verzonden naar het lichtkrant-tabblad ✓':(d.speech_error||'Test kon niet worden uitgevoerd'),d.ok?'ok':'error')}catch(e){flash(`Omroeptest mislukt: ${e.message}`,'error')}}
async function stopSpeech(){try{await api('/api/test-message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'stop-speech',speak:false,host_speak:false})});flash('Stop-opdracht naar lichtkrant gestuurd ✓','ok')}catch(e){flash(`Stoppen mislukt: ${e.message}`,'error')}}
async function tts(){try{const [d,h]=await Promise.all([api('/api/tts/status'),api('/api/health')]),e=$('#ttsStatus'),c=h.health?.display_client||{};let text=d.local_wav_available?'lokale WAV klaar':(d.online_fallback_available?'online fallback klaar':'TTS niet klaar'),ok=!!d.generator_available;if(c.audio_unlocked===false&&(Number(c.audio_attempts)>0||String(c.audio_last_mode||'')==='autoplay-locked')){text='browseraudio vergrendeld • klik op lichtkrant';ok=false}else if(Number(c.audio_failures)>0&&Number(c.audio_successes)===0){text='audiofout: '+String(c.audio_last_error||d.render_last_error||'onbekend').slice(0,62);ok=false}else if(Number(c.audio_successes)>0){text=`audio ok • ${c.audio_last_mode||d.render_last_engine||'WAV'}${d.render_last_voice?' • '+d.render_last_voice:''}`;ok=true}else if(d.render_last_voice){text+=` • ${d.render_last_voice}`}e.textContent=text;e.className='status-pill '+(ok?'online':'error')}catch{setText('#ttsStatus','offline')}}
async function vehicleDb(){
  try{
    const s=await api('/api/vehicles/status'),st=s.status||{},regions=st.selected_regions||[],cached=st.cached_regions||[];
    const rows=Object.entries(st.regions||{}),done=rows.filter(([,x])=>x?.ok).length;
    setText('#vehicleCount',st.count??'—');setText('#vehicleVersion',st.version||'4.1.1');
    const busy=st.running||st.force_pending;
    setText('#vehicleRegionStatus',busy?`bijwerken… (${Math.max(done,cached.length)}/${regions.length})`:(regions.length?`${Math.max(done,cached.length)}/${regions.length} regio’s`:'geen BRW-regio'));
    const detail=$('#vehicleSyncDetail');
    if(detail){
      if(st.last_error){detail.textContent=`Laatste fout: ${String(st.last_error).slice(0,420)}`;detail.dataset.kind='error'}
      else if(rows.length){
        detail.textContent=rows.map(([code,x])=>`${code}: ${x?.count??0} voertuigen${x?.source?' • '+x.source:''}${x?.cached?' • cache':''}${x?.pages>1?' • '+x.pages+' pagina’s':''}`).join('  |  ');detail.dataset.kind='ok';
      }else if(cached.length){
        const meta=st.region_meta||{};detail.textContent=cached.map(code=>`${code}: ${meta[code]?.count??'?'} voertuigen${meta[code]?.source?' • '+meta[code].source:''} • cache`).join('  |  ');detail.dataset.kind='ok';
      }else{detail.textContent=regions.length?'Nog geen regionale voertuigcache. Klik op Nu bijwerken.':'Geen brandweerregio geselecteerd.';detail.dataset.kind=''}
    }
    return st;
  }catch(e){setText('#vehicleCount','fout');setText('#vehicleRegionStatus',e.message);const d=$('#vehicleSyncDetail');if(d){d.textContent=e.message;d.dataset.kind='error'};throw e}
}
async function syncVehicles(){
  const b=$('#syncVehiclesBtn');b.disabled=true;b.textContent='Bijwerken…';
  try{
    await api('/api/vehicles/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({force:true})});
    let st=null;
    for(let i=0;i<80;i++){await new Promise(r=>setTimeout(r,750));st=await vehicleDb();if(!st.running&&!st.force_pending)break}
    st=await vehicleDb();
    if(st.running||st.force_pending){b.textContent='Nog bezig…';flash('Voertuigendatabase werkt nog op de achtergrond bij.','')}
    else if(st.last_error){b.textContent='Mislukt';flash(`Voertuigendatabase: ${st.last_error}`,'error')}
    else{b.textContent='Bijgewerkt ✓';flash(`Voertuigendatabase bijgewerkt: ${st.count} bekende voertuigen.`,'ok')}
  }catch(e){b.textContent='Mislukt';flash(`Voertuigendatabase: ${e.message}`,'error')}
  setTimeout(()=>{b.disabled=false;b.textContent='Nu bijwerken'},2400)
}
async function unknown(){try{const d=await api('/api/unknown-vehicles?limit=30'),rows=d.unknown||[];$('#unknownList').innerHTML=rows.length?rows.map(x=>`<div class="unknown-row"><b>${escapeHtml(x.callsign)}</b> • ${escapeHtml(x.last_city||'onbekende plaats')}<br><small>${escapeHtml(x.last_message||'')}</small></div>`).join(''):'<div class="unknown-row">Geen onbekende brandweerroepnummers 🎉</div>'}catch(e){$('#unknownList').textContent=e.message}}
let githubUpdateSettings={github_repo:'xSophie1119/lichtkrant',github_auto_check:true,github_auto_install:true,github_check_hours:6};
let githubUpdateStatus={};
function renderGithubUpdateSettings(x={}){
  githubUpdateSettings={...githubUpdateSettings,...x};
  if($('#githubRepoInput'))$('#githubRepoInput').value=githubUpdateSettings.github_repo||'xSophie1119/lichtkrant';
  if($('#githubAutoCheckInput'))$('#githubAutoCheckInput').checked=!!githubUpdateSettings.github_auto_check;
  if($('#githubAutoInstallInput'))$('#githubAutoInstallInput').checked=!!githubUpdateSettings.github_auto_install;
  if($('#githubCheckHoursInput'))$('#githubCheckHoursInput').value=String(githubUpdateSettings.github_check_hours||6);
}
async function loadGithubUpdateSettings(){try{const d=await api('/api/update/github/settings');renderGithubUpdateSettings(d.settings||{})}catch(e){setText('#updateRepoStatus','instellingen fout');setText('#updateDetail',e.message)}}
function renderUpdateStatus(st={}){
  githubUpdateStatus=st||{};
  setText('#updateCurrentVersion',st.current_version||'—');
  setText('#updateLatestVersion',st.latest_version||'nog niet gecontroleerd');
  setText('#updateRepoStatus',st.github_repo||githubUpdateSettings.github_repo||'niet ingesteld');
  const state=String(st.state||'idle');setText('#updateStateText',state);
  const pill=$('#updateStatusPill');if(pill){const available=!!st.available,err=state==='error';pill.textContent=err?'fout':available?`v${st.latest_version} beschikbaar`:state==='up-to-date'||state==='ready'?'actueel':state;pill.className='status-pill '+(err?'error':available?'':'online')}
  const detail=$('#updateDetail');if(detail){if(st.error){detail.textContent=`Updatefout: ${st.error}`;detail.dataset.kind='error'}else if(st.available){detail.textContent=`Nieuwe versie ${st.latest_version} beschikbaar${st.asset_name?' • '+st.asset_name:''}. ${st.message||''}`;detail.dataset.kind='ok'}else{detail.textContent=st.message||'GitHub Releases nog niet gecontroleerd.';detail.dataset.kind=''}}
  const install=$('#installUpdateBtn');if(install)install.disabled=!st.available||['downloading','validating','backup','installing','restarting','rollback'].includes(state);
}
async function updateStatus(){try{const d=await api('/api/update/status');renderUpdateStatus(d)}catch(e){setText('#updateStatusPill','offline');setText('#updateDetail',e.message)}}
async function saveUpdateSettings(){const b=$('#saveUpdateSettingsBtn');b.disabled=true;try{const payload={github_repo:($('#githubRepoInput').value||'').trim(),github_auto_check:$('#githubAutoCheckInput').checked,github_auto_install:$('#githubAutoInstallInput').checked,github_check_hours:Number($('#githubCheckHoursInput').value)||6};const d=await api('/api/update/github/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});renderGithubUpdateSettings(d.settings||payload);flash('GitHub update-instellingen opgeslagen ✓','ok');await updateStatus()}catch(e){flash(`Update-instellingen: ${e.message}`,'error')}finally{b.disabled=false}}
async function checkGithubUpdate(install=false){const b=$(install?'#installUpdateBtn':'#checkUpdateBtn');b.disabled=true;b.textContent=install?'Installeren…':'Controleren…';try{const d=await api('/api/update/github/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({install})});renderUpdateStatus(d.status||{});if(install){flash('Update gedownload. De monitor maakt een backup en herstart automatisch…','ok');setTimeout(updateStatus,2500)}else{flash(d.status?.available?`Versie ${d.status.latest_version} beschikbaar.`:'Je gebruikt de nieuwste versie ✓',d.status?.available?'':'ok')}}catch(e){flash(`GitHub update: ${e.message}`,'error');await updateStatus()}finally{if(!install){b.disabled=false;b.textContent='Controleer nu'}else{b.textContent='Update installeren'}}}
async function rollbackUpdate(){const b=$('#rollbackUpdateBtn');if(!confirm('Vorige programmaversie herstellen? Config, database en achtergrond blijven behouden.'))return;b.disabled=true;try{const d=await api('/api/update/rollback',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});flash(`Rollback naar ${d.target_version||'vorige versie'} gestart…`,'ok');setTimeout(updateStatus,2500)}catch(e){flash(`Rollback: ${e.message}`,'error');b.disabled=false}}
async function loadSetup(){try{const d=await api('/api/setup');setupProfile=d.setup||{};const regionMeta=new Map((setupProfile.regions||[]).map(r=>[r.slug,r]));const selected=Object.keys(setupProfile.region_disciplines||{});const tags=selected.map(slug=>regionMeta.get(slug)?.label||slug);$('#scopeTags').innerHTML=tags.map(x=>`<span>${escapeHtml(x)}</span>`).join('')||'<span>Nog niet ingesteld</span>';const owner=setupProfile.profile_type==='bedrijf'?(setupProfile.company_name||'Bedrijf'):(setupProfile.person_name||'Particulier');$('#profileTitle').textContent=(setupProfile.standplaats_city||setupProfile.standplaats)?`Standplaats ${setupProfile.standplaats_city||setupProfile.standplaats}`:'Installatieprofiel';$('#profileSummary').textContent=`${owner} • ${selected.length} regio${selected.length===1?'':'’s'} • ${(setupProfile.feed_urls||[]).length} RSS-bronnen. Wijzig regio’s en disciplines via de Configuratiewizard.`;$('#profileBadge').textContent=setupProfile.profile_type==='bedrijf'?'BEDRIJF':'PARTICULIER';const t=$('#testInput');if(t&&t.dataset.autoExample!=='0'){const place=setupProfile.standplaats_city||setupProfile.standplaats||'Utrecht';t.value=`P 1 BR woning Hoofdstraat ${place}`;t.dataset.autoExample='1';}}catch(e){$('#profileSummary').textContent=`Installatieprofiel laden mislukt: ${e.message}`}}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function init(){
  $('#saveBtn').addEventListener('click',save);$('#backgroundStyleInput').addEventListener('change',toggleBackgroundColor);$('#uploadBackgroundPhotoBtn')?.addEventListener('click',uploadBackgroundPhoto);$('#removeBackgroundPhotoBtn')?.addEventListener('click',removeBackgroundPhoto);$('#reconnectBtn').addEventListener('click',reconnect);$('#detectDisplayBtn').addEventListener('click',displayInfo);$('#displayOffBtn').addEventListener('click',()=>displayPower('off'));$('#displayOnBtn').addEventListener('click',()=>displayPower('on'));$('#testDisplayBtn').addEventListener('click',()=>testMessage(false));$('#testSpeakBtn').addEventListener('click',()=>testMessage(true));$('#voiceTestBtn').addEventListener('click',voiceTest);$('#stopSpeechBtn').addEventListener('click',stopSpeech);$('#refreshUnknownBtn').addEventListener('click',unknown);$('#syncVehiclesBtn').addEventListener('click',syncVehicles);$('#saveUpdateSettingsBtn')?.addEventListener('click',saveUpdateSettings);$('#checkUpdateBtn')?.addEventListener('click',()=>checkGithubUpdate(false));$('#installUpdateBtn')?.addEventListener('click',()=>checkGithubUpdate(true));$('#rollbackUpdateBtn')?.addEventListener('click',rollbackUpdate);
  Promise.allSettled([loadSetup(),loadSettings(),loadGithubUpdateSettings(),updateStatus(),status(),feeds(),displayInfo(),tts(),vehicleDb(),unknown()]);setInterval(status,15000);setInterval(updateStatus,30000);setInterval(unknown,30000);setInterval(tts,30000);setInterval(vehicleDb,60000);
}
init();
