'use strict';
const $=s=>document.querySelector(s);
const $$=s=>[...document.querySelectorAll(s)];
const DEFAULTS={
  name:'P2000 Monitor',services:['brandweer','ambulance','politie','lifeliner','knrm'],cities:[],keywords:[],
  nightMode:true,nightStart:'23:00',nightEnd:'07:00',messageMinutes:3,maxAgeMinutes:5,dateFormat:'dd-mm-yyyy',
  idleCentered:true,burnInProtection:true,burnInPixels:12,autoTextSize:true,darkLedPercent:4,vehicleHeader:true,displaySleep:false,
  speechEnabled:true,speechMode:'normal',masterVolume:100,speechCities:[],speechRate:.96,speechPitch:1,speechEngine:'online',speechDeviceVolumeDay:38,speechDeviceVolumeNight:20,speechDeviceVolumeUrgent:55,
  dispatchTuneEnabled:true,dispatchTuneDefault:'youtube',dispatchTuneBrandweer:'inherit',dispatchTuneAmbulance:'inherit',dispatchTunePolitie:'inherit',dispatchTuneLifeliner:'inherit',dispatchTuneKnrm:'inherit',dispatchTuneUrgent:'youtube',dispatchTuneYoutubeUrl:'https://www.youtube.com/watch?v=VleijwaD_-U',dispatchTuneYoutubeSeconds:5,dispatchTuneVolume:80,dispatchTuneCustomVersion:0,
  mapEnabled:true,mapZoom:16,backgroundStyle:'black',backgroundColor:'#020506',backgroundPhotoVersion:0,backgroundPhotoDarkness:.60,backgroundPhotoFit:'cover',kioskMonitor:'primary',idleStyle:'normal',idleLayout:'center',idleHeadline:'',idleSubline:'P2000 MELDINGEN HEBBEN DIRECT VOORRANG',idleShowName:true,idleShowDate:true,idleShowSeconds:true,idleShowStatus:true,idleClockScale:100,messageDisplayMode:'raw',idleDimEnabled:true,idleDimStart:'21:30',idleDimEnd:'07:00',idleDimMin:.42,
  idleDimEarliest:'20:30',smartSilenceEnabled:true,smartSilenceMinutes:30,postIncidentQuietEnabled:true,postIncidentQuietSeconds:20
};
let setupProfile=null;
let settings={...DEFAULTS};
async function api(path,opts={}){const {timeoutMs=12000,...fetchOpts}=opts||{},controller=!fetchOpts.signal&&typeof AbortController!=='undefined'?new AbortController():null,timer=controller?setTimeout(()=>controller.abort(),Math.max(500,timeoutMs)):null;try{const r=await fetch(path,{cache:'no-store',...fetchOpts,signal:fetchOpts.signal||controller?.signal});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`${r.status} ${r.statusText}`);return d}catch(e){if(e?.name==='AbortError')throw new Error(`Verzoek duurde langer dan ${Math.round(timeoutMs/1000)} seconden`);throw e}finally{if(timer)clearTimeout(timer)}}
function clamp(v,a,b,d){v=Number(v);return Number.isFinite(v)?Math.max(a,Math.min(b,v)):d}
function parseList(v){return [...new Set(String(v||'').split(/[\n,;]+/).map(x=>x.trim()).filter(Boolean))].slice(0,50)}
const TUNE_OPTIONS=[['inherit','Overnemen van standaard'],['none','Geen deuntje'],['builtin:classic','Kazerne klassiek'],['builtin:double','Dubbele attentietoon'],['builtin:rising','Oplopend signaal'],['builtin:urgent','Urgent driedubbel'],['youtube','YouTube-deuntje'],['custom','Eigen MP3 / WAV / OGG']];
function initTuneSelects(){for(const el of $$('[data-tune-select]')){const isDefault=el.hasAttribute('data-default-tune');el.innerHTML=TUNE_OPTIONS.filter(([v])=>!isDefault||v!=='inherit').map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}}
function updateTuneVolumeLabel(){setText('#dispatchTuneVolumeValue',Math.round(clamp($('#dispatchTuneVolumeInput')?.value,0,100,80)))}
function tuneSettingsFromForm(){return {
  dispatchTuneEnabled:$('#dispatchTuneEnabledInput')?.checked!==false,
  dispatchTuneDefault:$('#dispatchTuneDefaultInput')?.value||'none',dispatchTuneBrandweer:$('#dispatchTuneBrandweerInput')?.value||'inherit',dispatchTuneAmbulance:$('#dispatchTuneAmbulanceInput')?.value||'inherit',dispatchTunePolitie:$('#dispatchTunePolitieInput')?.value||'inherit',dispatchTuneLifeliner:$('#dispatchTuneLifelinerInput')?.value||'inherit',dispatchTuneKnrm:$('#dispatchTuneKnrmInput')?.value||'inherit',dispatchTuneUrgent:$('#dispatchTuneUrgentInput')?.value||'inherit',
  dispatchTuneYoutubeUrl:($('#dispatchTuneYoutubeUrlInput')?.value||'').trim(),dispatchTuneYoutubeSeconds:clamp($('#dispatchTuneYoutubeSecondsInput')?.value,1,15,5),dispatchTuneVolume:clamp($('#dispatchTuneVolumeInput')?.value,0,100,80),dispatchTuneCustomVersion:Number(settings.dispatchTuneCustomVersion)||0
}}
let tuneSaveTimer=null,tuneSaveSerial=0;
function tuneStatus(text,kind=''){const e=$('#tuneStatus');if(!e)return;e.textContent=text;e.className='status-pill '+(kind==='ok'?'online':kind==='error'?'error':'')}
async function saveTuneSettings(opts={}){const serial=++tuneSaveSerial;tuneStatus('opslaan…');try{const d=await api('/api/tune/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(tuneSettingsFromForm())});if(serial!==tuneSaveSerial)return d.settings||{};settings={...settings,...(d.settings||{})};tuneStatus('opgeslagen','ok');if(!opts.silent)flash('Toontjes opgeslagen ✓','ok');return d.settings||{}}catch(e){if(serial===tuneSaveSerial)tuneStatus('fout','error');if(!opts.silent)flash(`Toontjes opslaan mislukt: ${e.message}`,'error');throw e}}
function scheduleTuneSave(){clearTimeout(tuneSaveTimer);tuneStatus('gewijzigd');tuneSaveTimer=setTimeout(()=>saveTuneSettings({silent:true}).catch(()=>{}),450)}
function toggleBackgroundColor(){const style=$('#backgroundStyleInput')?.value||'black',f=$('#backgroundColorField'),p=$('#backgroundPhotoField');if(f)f.style.display=style==='custom'?'':'none';if(p)p.style.display=style==='photo'?'':'none'}
function setText(sel,v){const e=$(sel);if(e)e.textContent=v??'—'}
let flashTimer=null;function flash(text,kind=''){const el=$('#pageFeedback')||$('#testStatus');if(!el)return;el.textContent=text;el.dataset.kind=kind;el.hidden=false;clearTimeout(flashTimer);flashTimer=setTimeout(()=>{el.hidden=true},5200)}
function formToSettings(){
  return {...settings,
    name:($('#nameInput').value||'P2000 Monitor').trim().slice(0,30),
    services:$$('[data-service]').filter(x=>x.checked).map(x=>x.dataset.service),cities:[],keywords:[],
    messageMinutes:clamp($('#messageMinutesInput').value,.25,15,3),maxAgeMinutes:clamp($('#maxAgeMinutesInput').value,.25,30,5),
    vehicleHeader:$('#vehicleHeaderInput').checked,mapEnabled:$('#mapEnabledInput').checked,burnInProtection:$('#burnInProtectionInput').checked,
    speechEnabled:$('#speechEnabledInput').checked,speechMode:$('#speechModeInput')?.value||'normal',masterVolume:clamp($('#masterVolumeInput')?.value,0,100,100),speechEngine:'online',speechCities:parseList($('#speechCitiesInput').value),
    speechRate:clamp($('#speechRateInput').value,.65,1.25,.96),speechPitch:clamp($('#speechPitchInput').value,.75,1.3,1),
    dispatchTuneEnabled:$('#dispatchTuneEnabledInput').checked,dispatchTuneDefault:$('#dispatchTuneDefaultInput').value||'none',dispatchTuneBrandweer:$('#dispatchTuneBrandweerInput').value||'inherit',dispatchTuneAmbulance:$('#dispatchTuneAmbulanceInput').value||'inherit',dispatchTunePolitie:$('#dispatchTunePolitieInput').value||'inherit',dispatchTuneLifeliner:$('#dispatchTuneLifelinerInput').value||'inherit',dispatchTuneKnrm:$('#dispatchTuneKnrmInput').value||'inherit',dispatchTuneUrgent:$('#dispatchTuneUrgentInput').value||'inherit',dispatchTuneYoutubeUrl:($('#dispatchTuneYoutubeUrlInput').value||'').trim(),dispatchTuneYoutubeSeconds:clamp($('#dispatchTuneYoutubeSecondsInput').value,1,15,5),dispatchTuneVolume:clamp($('#dispatchTuneVolumeInput').value,0,100,80),dispatchTuneCustomVersion:Number(settings.dispatchTuneCustomVersion)||0,
    backgroundStyle:$('#backgroundStyleInput').value||'black',backgroundColor:$('#backgroundColorInput').value||'#020506',backgroundPhotoVersion:Number(settings.backgroundPhotoVersion)||0,backgroundPhotoDarkness:clamp($('#backgroundPhotoDarknessInput')?.value,0,90,60)/100,backgroundPhotoFit:$('#backgroundPhotoFitInput')?.value||'cover',kioskMonitor:$('#kioskMonitorInput').value||'primary',displaySleep:$('#displaySleepInput').checked,nightMode:$('#nightModeInput').checked,nightStart:$('#nightStartInput').value||'23:00',nightEnd:$('#nightEndInput').value||'07:00',
    idleLayout:$('#idleLayoutInput')?.value||'center',idleHeadline:($('#idleHeadlineInput')?.value||'').trim().slice(0,90),idleSubline:($('#idleSublineInput')?.value||'').trim().slice(0,160),idleShowName:$('#idleShowNameInput')?.checked!==false,idleShowDate:$('#idleShowDateInput')?.checked!==false,idleShowSeconds:$('#idleShowSecondsInput')?.checked!==false,idleShowStatus:$('#idleShowStatusInput')?.checked!==false,idleClockScale:clamp($('#idleClockScaleInput')?.value,65,135,100),messageDisplayMode:$('#messageDisplayModeInput')?.value||'raw'
  };
}
function renderSettings(s){
  settings={...DEFAULTS,...s};
  $('#nameInput').value=settings.name;$('#messageMinutesInput').value=settings.messageMinutes;$('#maxAgeMinutesInput').value=settings.maxAgeMinutes;
  $('#vehicleHeaderInput').checked=settings.vehicleHeader!==false;$('#mapEnabledInput').checked=settings.mapEnabled!==false;$('#burnInProtectionInput').checked=settings.burnInProtection!==false;
  $('#speechEnabledInput').checked=settings.speechEnabled!==false;settings.speechMode=['normal','priority','mute'].includes(String(settings.speechMode))?String(settings.speechMode):'normal';settings.masterVolume=clamp(settings.masterVolume,0,100,100);if($('#speechModeInput'))$('#speechModeInput').value=settings.speechMode;if($('#masterVolumeInput'))$('#masterVolumeInput').value=settings.masterVolume;setText('#masterVolumeValue',Math.round(settings.masterVolume));setText('#quickVolumeValue',Math.round(settings.masterVolume));if($('#quickVolumeInput'))$('#quickVolumeInput').value=settings.masterVolume;settings.speechEngine='online';$('#speechEngineInput').value='online';$('#speechCitiesInput').value=(settings.speechCities||[]).join(', ');$('#speechRateInput').value=settings.speechRate;$('#speechPitchInput').value=settings.speechPitch;renderQuickMode();
  $('#dispatchTuneEnabledInput').checked=settings.dispatchTuneEnabled!==false;$('#dispatchTuneDefaultInput').value=settings.dispatchTuneDefault||'youtube';$('#dispatchTuneBrandweerInput').value=settings.dispatchTuneBrandweer||'inherit';$('#dispatchTuneAmbulanceInput').value=settings.dispatchTuneAmbulance||'inherit';$('#dispatchTunePolitieInput').value=settings.dispatchTunePolitie||'inherit';$('#dispatchTuneLifelinerInput').value=settings.dispatchTuneLifeliner||'inherit';$('#dispatchTuneKnrmInput').value=settings.dispatchTuneKnrm||'inherit';$('#dispatchTuneUrgentInput').value=settings.dispatchTuneUrgent||'inherit';$('#dispatchTuneYoutubeUrlInput').value=settings.dispatchTuneYoutubeUrl||'https://www.youtube.com/watch?v=VleijwaD_-U';$('#dispatchTuneYoutubeSecondsInput').value=settings.dispatchTuneYoutubeSeconds||5;$('#dispatchTuneVolumeInput').value=settings.dispatchTuneVolume??80;updateTuneVolumeLabel();tuneFileInfo();tuneStatus('opgeslagen','ok');
  $('#backgroundStyleInput').value=settings.backgroundStyle||'black';$('#backgroundColorInput').value=settings.backgroundColor||'#020506';if($('#backgroundPhotoDarknessInput'))$('#backgroundPhotoDarknessInput').value=Math.round(clamp(settings.backgroundPhotoDarkness,0,.9,.6)*100);if($('#backgroundPhotoFitInput'))$('#backgroundPhotoFitInput').value=settings.backgroundPhotoFit||'cover';toggleBackgroundColor();backgroundPhotoInfo();
  $('#kioskMonitorInput').value=settings.kioskMonitor||'primary';$('#displaySleepInput').checked=!!settings.displaySleep;$('#nightModeInput').checked=settings.nightMode!==false;$('#nightStartInput').value=settings.nightStart||'23:00';$('#nightEndInput').value=settings.nightEnd||'07:00';
  if($('#idleLayoutInput'))$('#idleLayoutInput').value=settings.idleLayout||'center';if($('#idleHeadlineInput'))$('#idleHeadlineInput').value=settings.idleHeadline||'';if($('#idleSublineInput'))$('#idleSublineInput').value=settings.idleSubline||'P2000 MELDINGEN HEBBEN DIRECT VOORRANG';if($('#idleShowNameInput'))$('#idleShowNameInput').checked=settings.idleShowName!==false;if($('#idleShowDateInput'))$('#idleShowDateInput').checked=settings.idleShowDate!==false;if($('#idleShowSecondsInput'))$('#idleShowSecondsInput').checked=settings.idleShowSeconds!==false;if($('#idleShowStatusInput'))$('#idleShowStatusInput').checked=settings.idleShowStatus!==false;if($('#idleClockScaleInput'))$('#idleClockScaleInput').value=clamp(settings.idleClockScale,65,135,100);setText('#idleClockScaleValue',Math.round(clamp(settings.idleClockScale,65,135,100)));if($('#messageDisplayModeInput'))$('#messageDisplayModeInput').value=settings.messageDisplayMode||'raw';renderIdleBuilderPreview();
  const active=new Set(settings.services||[]);$$('[data-service]').forEach(x=>x.checked=active.has(x.dataset.service));
}
let quickVolumeTimer=null,quickVolumePending=null;
function syncVolumeControls(value){const safe=Math.round(clamp(value,0,100,100));if($('#masterVolumeInput'))$('#masterVolumeInput').value=safe;if($('#quickVolumeInput'))$('#quickVolumeInput').value=safe;setText('#masterVolumeValue',safe);setText('#quickVolumeValue',safe);return safe}
function scheduleQuickVolume(value,{immediate=false}={}){quickVolumePending=syncVolumeControls(value);clearTimeout(quickVolumeTimer);const send=()=>{const pending=quickVolumePending;quickVolumePending=null;quickVolumeTimer=null;quickAction('volume',{value:pending})};if(immediate)send();else quickVolumeTimer=setTimeout(send,220)}
async function loadSettings(){try{const d=await api('/api/settings');renderSettings(d.settings||{})}catch(e){flash(`Instellingen laden mislukt: ${e.message}`,'error');renderSettings({})}}
async function save(){const b=$('#saveBtn');b.disabled=true;b.textContent='Opslaan…';try{const d=await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(formToSettings())});renderSettings(d.settings||formToSettings());flash('Instellingen opgeslagen ✓','ok')}catch(e){flash(`Opslaan mislukt: ${e.message}`,'error')}finally{b.disabled=false;b.textContent='Instellingen opslaan'}}
async function backgroundPhotoInfo(){const el=$('#backgroundPhotoStatus');if(!el)return;try{const d=await api('/api/background/info');if(d.exists){el.textContent=`Foto opgeslagen • ${d.type||'afbeelding'} • ${(Number(d.bytes||0)/1024/1024).toFixed(1)} MB`;settings.backgroundPhotoVersion=Number(d.version)||settings.backgroundPhotoVersion||0}else el.textContent='Nog geen achtergrondfoto opgeslagen.'}catch(e){el.textContent=`Fotostatus niet beschikbaar: ${e.message}`}}
async function uploadBackgroundPhoto(){const input=$('#backgroundPhotoInput'),file=input?.files?.[0],btn=$('#uploadBackgroundPhotoBtn');if(!file)return flash('Kies eerst een JPG, PNG of WebP.','error');if(file.size>15*1024*1024)return flash('Foto is groter dan 15 MB. Kies een kleinere afbeelding.','error');btn.disabled=true;btn.textContent='Uploaden…';try{const d=await api('/api/background/upload',{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream','X-File-Name':encodeURIComponent(file.name||'background')},body:file,timeoutMs:45000});settings.backgroundPhotoVersion=Number(d.version)||Date.now();$('#backgroundStyleInput').value='photo';toggleBackgroundColor();const saved=await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(formToSettings())});renderSettings(saved.settings||formToSettings());flash('Achtergrondfoto opgeslagen ✓','ok');await backgroundPhotoInfo()}catch(e){flash(`Foto opslaan mislukt: ${e.message}`,'error')}finally{btn.disabled=false;btn.textContent='Foto opslaan'}}
async function removeBackgroundPhoto(){const btn=$('#removeBackgroundPhotoBtn');btn.disabled=true;try{const d=await api('/api/background/remove',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});settings.backgroundPhotoVersion=0;if($('#backgroundStyleInput')?.value==='photo')$('#backgroundStyleInput').value='black';toggleBackgroundColor();const saved=await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(formToSettings())});renderSettings(saved.settings||formToSettings());flash(d.ok?'Achtergrondfoto verwijderd ✓':'Foto verwijderen mislukt',d.ok?'ok':'error');await backgroundPhotoInfo()}catch(e){flash(`Foto verwijderen mislukt: ${e.message}`,'error')}finally{btn.disabled=false}}
async function tuneFileInfo(){const el=$('#dispatchTuneFileStatus');if(!el)return;try{const d=await api('/api/tune/info');if(d.exists){el.textContent=`Opgeslagen: ${d.name||'custom'} • ${(Number(d.bytes||0)/1024/1024).toFixed(1)} MB`;settings.dispatchTuneCustomVersion=Number(d.version)||settings.dispatchTuneCustomVersion||0}else el.textContent='Nog geen eigen deuntje geladen.'}catch(e){el.textContent=`Audiostatus niet beschikbaar: ${e.message}`}}
async function uploadDispatchTune(){const input=$('#dispatchTuneFileInput'),file=input?.files?.[0],btn=$('#uploadDispatchTuneBtn');if(!file)return flash('Kies eerst een MP3, WAV of OGG.','error');if(file.size>12*1024*1024)return flash('Deuntje is groter dan 12 MB.','error');btn.disabled=true;btn.textContent='Uploaden…';try{const d=await api('/api/tune/upload',{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream','X-File-Name':encodeURIComponent(file.name||'deuntje')},body:file,timeoutMs:45000});settings.dispatchTuneCustomVersion=Number(d.version)||Date.now();await saveTuneSettings({silent:true});flash('Eigen deuntje opgeslagen ✓','ok');await tuneFileInfo()}catch(e){flash(`Deuntje opslaan mislukt: ${e.message}`,'error')}finally{btn.disabled=false;btn.textContent='Eigen deuntje opslaan'}}
async function removeDispatchTune(){const btn=$('#removeDispatchTuneBtn');btn.disabled=true;try{const d=await api('/api/tune/remove',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});settings.dispatchTuneCustomVersion=0;await saveTuneSettings({silent:true});flash(d.ok?'Eigen deuntje verwijderd ✓':'Verwijderen mislukt',d.ok?'ok':'error');await tuneFileInfo()}catch(e){flash(`Deuntje verwijderen mislukt: ${e.message}`,'error')}finally{btn.disabled=false}}
function testToken(kind){return `${kind}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`}
async function waitForTestResult(token,timeoutMs=12000){const until=Date.now()+timeoutMs;while(Date.now()<until){await new Promise(r=>setTimeout(r,350));try{const d=await api(`/api/test-status?token=${encodeURIComponent(token)}`),result=d.result||{};if(result.status==='completed'||result.status==='error')return result}catch{}}throw new Error('Geen afspeelbevestiging van de lichtkrant ontvangen')}
async function persistCurrentSettings(){const d=await api('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(formToSettings())});renderSettings(d.settings||formToSettings());return d.settings||settings}
async function testDispatchTune(){const b=$('#testDispatchTuneBtn');b.disabled=true;try{await saveTuneSettings({silent:true});const token=testToken('tune'),choice=$('#dispatchTuneDefaultInput').value||'none';flash('Deuntje op lichtkrant testen…');await api('/api/test-message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,mode:'tune-only',service:'brandweer',priority:'P1',speak:false,force_audio:true,tune_choice:choice})});const result=await waitForTestResult(token,18000);flash(result.ok?`Deuntje werkt ✓ ${result.detail||''}`:`Deuntjetest mislukt: ${result.detail||'onbekende fout'}`,result.ok?'ok':'error')}catch(e){flash(`Deuntjetest mislukt: ${e.message}`,'error')}finally{b.disabled=false}}
async function status(){try{const d=await api('/api/status');setText('#versionStatus',d.version);setText('#feedStatus',d.feed_status||'—');setText('#todayStatus',d.messages_today??0);setText('#lastMessageStatus',d.last_message?new Date(d.last_message).toLocaleString('nl-NL'):'nog geen');setText('#scopeStatus',d.scope);setText('#errorStatus',d.last_error||'geen');setText('#quickFeedStatus',d.feed_status||'—');const p=$('#controlStatus');p.textContent=d.feed_status==='online'?'online':(d.feed_status||'onbekend');p.className='status-pill '+(d.feed_status==='online'?'online':'error');if(d.supervisor)renderSupervisor(d.supervisor)}catch(e){setText('#controlStatus','offline');$('#controlStatus').className='status-pill error';setText('#quickFeedStatus','offline');setText('#errorStatus',e.message)}}
async function feeds(){try{const [d,h]=await Promise.all([api('/api/feed-config'),api('/api/health')]),cfg=d.config||{},metrics=h.health?.feed_metrics||[],metric=new Map(metrics.map(x=>[x.url,x]));if($('#feed112nuInput'))$('#feed112nuInput').checked=cfg.feed_112nu_enabled!==false;const groups=[['HOOFD • 112-NU',cfg.primary_feed_urls||[]],['RACE/FALLBACK',cfg.race_feed_urls||[]],['EXTRA',cfg.supplemental_feed_urls||[]],['FALLBACK',cfg.fallback_feed_urls||[]]];const rows=[];for(const [role,urls] of groups)for(const u of urls){const m=metric.get(u)||{},lat=m.latency_p50_seconds==null?'—':`${Number(m.latency_p50_seconds).toFixed(1)}s`,fetch=m.fetch_p50_ms==null?'—':`${Math.round(m.fetch_p50_ms)}ms`;rows.push(`<div class="feed-row"><b>${role}</b> • ${escapeHtml(m.status||'wachten')} • fetch ${fetch} • bronvertraging ${lat} • wins ${Number(m.wins)||0}<br><code>${escapeHtml(u)}</code></div>`)}$('#feedList').innerHTML=rows.join('')||'<div class="feed-row">Geen feeds ingesteld</div>'}catch(e){$('#feedList').textContent=e.message}}
async function save112NuToggle(){const el=$('#feed112nuInput');if(el){el.checked=true;el.disabled=true}}
async function reconnect(){const b=$('#reconnectBtn');b.disabled=true;b.textContent='Herverbinden…';try{await api('/api/feeds/reconnect',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});b.textContent='Aangevraagd ✓';setTimeout(status,1200)}catch{b.textContent='Mislukt'}setTimeout(()=>{b.disabled=false;b.textContent='Feeds opnieuw verbinden'},1800)}
async function displayInfo(){
  try{
    const d=await api('/api/display/info'),x=d.display||{},rows=Array.isArray(x.monitors)?x.monitors:[],sel=$('#kioskMonitorInput');
    // Backend is source of truth. Using the local DEFAULTS value here caused a
    // race where a saved second monitor was silently reset to primary.
    const wanted=String(x.selected_monitor_id||settings.kioskMonitor||'primary');
    const valueOf=r=>String(r.selector||r.device||r.fingerprint||r.id||'primary');
    if(sel&&rows.length){
      sel.innerHTML=rows.map((r,i)=>`<option value="${escapeHtml(valueOf(r)||String(i+1))}">${escapeHtml(r.label||`Scherm ${i+1}`)}${Number.isFinite(r.x)&&Number.isFinite(r.y)?` • ${r.x},${r.y}`:''}</option>`).join('');
      let chosen=rows.find(r=>[r.selector,r.fingerprint,r.device,r.id].map(v=>String(v||'')).includes(wanted));
      if(chosen){
        sel.value=valueOf(chosen);
        settings.kioskMonitor=sel.value;
        setText('#kioskMonitorHint',`Actief: ${chosen.label||sel.value} • positie ${chosen.x},${chosen.y}. Een nieuwe keuze wordt direct toegepast en de kiosk opnieuw geplaatst.`);
      }else if(wanted&&!['primary','primair','auto'].includes(wanted.toLowerCase())){
        // Preserve a stable monitor fingerprint when HDMI/DP is temporarily
        // disconnected; otherwise saving an unrelated setting loses the choice.
        const opt=document.createElement('option');opt.value=wanted;opt.textContent='Opgeslagen scherm • momenteel niet aangesloten';sel.prepend(opt);sel.value=wanted;
        settings.kioskMonitor=wanted;
        setText('#kioskMonitorHint','Het opgeslagen scherm is momenteel niet gevonden. De keuze blijft bewaard en wordt gebruikt zodra het scherm terug is.');
      }else{
        chosen=rows.find(r=>r.primary)||rows[0];sel.value=valueOf(chosen);settings.kioskMonitor=sel.value;
      }
    }
    const e=$('#displayStatus'),platform=x.platform==='linux'?`Linux ${x.session||''}`.trim():(x.platform==='windows'?'Windows':(x.platform||'systeem'));
    e.textContent=x.connected?`${rows.length||1} scherm${rows.length===1?'':'en'} • ${platform}${x.method?' • '+x.method:''}`:`${platform} • detectie beperkt`;
    e.className='status-pill '+(x.connected?'online':(rows.length?'':'error'));
    return x;
  }catch(e){setText('#displayStatus','fout');throw e}
}
async function applyDisplaySelection(){
  const sel=$('#kioskMonitorInput'),btn=$('#applyDisplayBtn'),selector=sel?.value||'primary';
  if(btn){btn.disabled=true;btn.textContent='Verplaatsen…'}
  try{
    const d=await api('/api/display/select',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({selector})});
    settings={...settings,...(d.settings||{}),kioskMonitor:d.selector||selector};
    const m=d.selected_monitor||{};
    flash(`Lichtkrant verplaatst naar ${m.label||m.device||'gekozen scherm'} ✓`,'ok');
    setTimeout(()=>displayInfo().catch(()=>{}),900);
    return d;
  }catch(e){flash(`Scherm wisselen mislukt: ${e.message}`,'error');await displayInfo().catch(()=>{})}
  finally{if(btn){btn.disabled=false;btn.textContent='Nu toepassen'}}
}
async function displayPower(mode){const id=mode==='on'?'#displayOnBtn':'#displayOffBtn',b=$(id);b.disabled=true;try{const d=await api('/api/display/power',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:mode,manual:true})});flash(d.ok?`Scherm ${mode==='on'?'aan':'uit'} ✓${d.method?' • '+d.method:''}`:`Schermactie niet beschikbaar: ${d.error||d.status}`,d.ok?'ok':'error');displayInfo()}catch(e){flash(`Schermactie mislukt: ${e.message}`,'error')}finally{b.disabled=false}}
function inferCity(raw){const preferred=String(setupProfile?.standplaats_city||setupProfile?.standplaats||'').trim();if(preferred&&String(raw).toLowerCase().includes(preferred.toLowerCase()))return preferred;return preferred}
function inferService(raw){const s=String(raw).toUpperCase();if(/\bLIFELINER\b|(?<!\d)(?:13[- ]?991|17[- ]?992|08[- ]?993)(?!\d)/.test(s))return'lifeliner';if(/\bASS\.?\s*(?:AMBU|POL)\b|\bBR(?:AND)?\b/.test(s))return'brandweer';if(/\bPOLITIE\b/.test(s))return'politie';if(/\bA[012]\b|\bB[12]\b|\bAMBU(?:LANCE)?\b|\bMMT\b/.test(s))return'ambulance';return'brandweer'}
async function testMessage(speak){const raw=$('#testInput').value.trim();if(!raw)return flash('Vul eerst een P2000-regel in.','error');const city=inferCity(raw),service=inferService(raw);flash(speak?'Testmelding + omroep…':'Testmelding tonen…');const payload={title:raw,summary:raw,city,service,priority:/\bP\s*2\b/i.test(raw)?'P2':(/\bP\s*3\b/i.test(raw)?'P3':'P1'),speak,host_speak:false,duration_ms:60000};if(speak&&settings.speechEngine==='online'){payload.host_speak=false}try{const d=await api('/api/test-message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});flash(d.ok?'Test verzonden ✓':(d.speech_error||'Test kon niet worden uitgevoerd'),d.ok?'ok':'error')}catch(e){flash(`Test mislukt: ${e.message}`,'error')}}
async function voiceTest(){const b=$('#voiceTestBtn');b.disabled=true;try{await persistCurrentSettings();flash('Omroep op lichtkrant testen…');const place=setupProfile?.standplaats_city||setupProfile?.standplaats||'de ingestelde standplaats';const text=`Brand woning aan de Hoofdstraat in ${place}. Eerste eenheden gealarmeerd.`;const token=testToken('speech');await api('/api/test-message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,mode:'speech-only',speech_text:text,speak:true,service:'brandweer',host_speak:false,force_audio:true})});const result=await waitForTestResult(token,35000);flash(result.ok?`Omroep werkt ✓ ${result.detail||''}`:`Omroeptest mislukt: ${result.detail||'onbekende fout'}`,result.ok?'ok':'error')}catch(e){flash(`Omroeptest mislukt: ${e.message}`,'error')}finally{b.disabled=false}}
async function stopSpeech(){try{await api('/api/test-message',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode:'stop-speech',speak:false,host_speak:false})});flash('Stop-opdracht naar lichtkrant gestuurd ✓','ok')}catch(e){flash(`Stoppen mislukt: ${e.message}`,'error')}}
async function tts(){try{const [d,h]=await Promise.all([api('/api/tts/status'),api('/api/health')]),e=$('#ttsStatus'),c=h.health?.display_client||{};let text=d.local_wav_available?'lokale WAV klaar':(d.online_fallback_available?'online fallback klaar':'TTS niet klaar'),ok=!!d.generator_available;if(c.audio_unlocked===false&&(Number(c.audio_attempts)>0||String(c.audio_last_mode||'')==='autoplay-locked')){text='browseraudio vergrendeld • klik op lichtkrant';ok=false}else if(Number(c.audio_failures)>0&&Number(c.audio_successes)===0){text='audiofout: '+String(c.audio_last_error||d.render_last_error||'onbekend').slice(0,62);ok=false}else if(Number(c.audio_successes)>0){text=`audio ok • ${c.audio_last_mode||d.render_last_engine||'WAV'}${d.render_last_voice?' • '+d.render_last_voice:''}`;ok=true}else if(d.render_last_voice){text+=` • ${d.render_last_voice}`}e.textContent=text;e.className='status-pill '+(ok?'online':'error')}catch{setText('#ttsStatus','offline')}}
let swApiConfig={};
function shortDateTime(value){if(!value)return '—';try{return new Intl.DateTimeFormat('nl-NL',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date(value))}catch{return String(value)}}
function renderSwApiStatus(st={}){
  const online=st.online===true?'online':(st.online===false?'offline':'onbekend');setText('#swApiOnline',online);
  const key=st.key_configured?(st.key_valid===true?'geldig':(st.key_valid===false?'ongeldig':'ingesteld • nog niet getest')):'niet ingesteld';setText('#swApiKeyStatus',key);
  setText('#swApiUnitCount',st.unit_count??0);setText('#swApiLastSync',shortDateTime(st.last_sync));
  const h=$('#swApiSecretHint');if(h&&st.secret_storage)h.textContent=`Backend-only opslag: ${st.secret_storage}. De key wordt nooit via /api/settings, GitHub-sync of de lichtkrantfrontend teruggestuurd.`;
}
async function loadSwApiConfig(){try{const d=await api('/api/roepnummer-api/config');swApiConfig=d.config||{};renderSwApiStatus(d.status||{});if($('#swApiBaseUrl'))$('#swApiBaseUrl').value=swApiConfig.base_url||'https://swmediaproducties.nl/roepnummers-api/v1';return d}catch(e){setText('#swApiOnline','fout');throw e}}
async function saveSwApiKey(){const b=$('#saveSwApiKeyBtn'),key=$('#swApiKeyInput')?.value?.trim()||'';if(!key)return flash('Vul eerst een API-key in.','error');b.disabled=true;try{const d=await api('/api/roepnummer-api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({api_key:key})});$('#swApiKeyInput').value='';renderSwApiStatus(d.status||{});flash('API-key veilig opgeslagen. Synchronisatie/test gestart ✓','ok');for(let i=0;i<24;i++){await new Promise(r=>setTimeout(r,500));const x=await api('/api/roepnummer-api/status');renderSwApiStatus(x.status||{});if(!x.status?.running){if(x.status?.key_valid)flash(`Roepnummer API werkt: ${x.status.unit_count||0} eenheden geladen ✓`,'ok');else if(x.status?.last_error)flash(`Roepnummer API: ${x.status.last_error}`,'error');break}}await vehicleDb()}catch(e){flash(`API-key opslaan mislukt: ${e.message}`,'error')}finally{b.disabled=false}}
async function clearSwApiKey(){if(!confirm('API-key verwijderen? De laatst gedownloade cache blijft als offline fallback beschikbaar.'))return;try{const d=await api('/api/roepnummer-api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({clear_key:true})});renderSwApiStatus(d.status||{});flash('API-key verwijderd. Lokale cache blijft behouden.','ok')}catch(e){flash(`API-key verwijderen mislukt: ${e.message}`,'error')}}
async function vehicleDb(){
  try{
    const s=await api('/api/vehicles/status'),st=s.status||{},regions=st.selected_regions||[],cached=(st.cached_regions||[]).filter(x=>x!=='sw-api');
    const sw=st.sw_api||{};renderSwApiStatus(sw);
    const rows=Object.entries(st.regions||{}),done=rows.filter(([,x])=>x?.ok).length;
    setText('#vehicleCount',st.count??'—');setText('#vehicleVersion',st.version||'4.4.15');
    const busy=st.running||st.force_pending;
    setText('#vehicleRegionStatus',busy?`bijwerken… (${Math.max(done,cached.length)}/${regions.length})`:(regions.length?`${Math.max(done,cached.length)}/${regions.length} regio’s`:'geen BRW-regio'));
    const detail=$('#vehicleSyncDetail');
    if(detail){
      if(sw.last_error&&!sw.key_valid){detail.textContent=`SW API: ${String(sw.last_error).slice(0,320)} • lokale cache blijft actief${sw.unit_count?` (${sw.unit_count} eenheden)`:''}`;detail.dataset.kind='error'}
      else if(sw.key_valid){detail.textContent=`SW Mediaproducties API online • ${sw.unit_count||0} eenheden • ${sw.pages||'?'} pagina('s) • sync ${shortDateTime(sw.last_sync)}`;detail.dataset.kind='ok'}
      else if(st.last_error){detail.textContent=`Fallback-fout: ${String(st.last_error).slice(0,420)}`;detail.dataset.kind='error'}
      else if(rows.length){
        detail.textContent=rows.map(([code,x])=>`${code}: ${x?.count??0} voertuigen${x?.source?' • '+x.source:''}${x?.cached?' • cache':''}${x?.pages>1?' • '+x.pages+' pagina’s':''}`).join('  |  ');detail.dataset.kind='ok';
      }else if(cached.length){
        const meta=st.region_meta||{};detail.textContent=cached.map(code=>`${code}: ${meta[code]?.count??'?'} voertuigen${meta[code]?.source?' • '+meta[code].source:''} • cache`).join('  |  ');detail.dataset.kind='ok';
      }else{detail.textContent=regions.length?'Nog geen regionale fallbackcache. Klik op Nu synchroniseren.':'Geen brandweerregio geselecteerd.';detail.dataset.kind=''}
    }
    return st;
  }catch(e){setText('#vehicleCount','fout');setText('#vehicleRegionStatus',e.message);const d=$('#vehicleSyncDetail');if(d){d.textContent=e.message;d.dataset.kind='error'};throw e}
}
async function syncVehicles(){
  const b=$('#syncVehiclesBtn');b.disabled=true;b.textContent='Bijwerken…';
  try{
    await api('/api/vehicles/sync',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({force:true}),timeoutMs:60000});
    let st=null;
    for(let i=0;i<80;i++){await new Promise(r=>setTimeout(r,750));st=await vehicleDb();if(!st.running&&!st.force_pending)break}
    st=await vehicleDb();
    if(st.running||st.force_pending){b.textContent='Nog bezig…';flash('Voertuigendatabase werkt nog op de achtergrond bij.','')}
    else if(st.last_error){b.textContent='Mislukt';flash(`Voertuigendatabase: ${st.last_error}`,'error')}
    else{b.textContent='Bijgewerkt ✓';const sw=st.sw_api||{};flash(sw.key_valid?`SW Roepnummer API bijgewerkt: ${sw.unit_count||0} eenheden • ${st.count} totaal bekend.`:`Voertuigendatabase bijgewerkt: ${st.count} bekende voertuigen.`,'ok')}
  }catch(e){b.textContent='Mislukt';flash(`Voertuigendatabase: ${e.message}`,'error')}
  setTimeout(()=>{b.disabled=false;b.textContent='Nu synchroniseren'},2400)
}
let vehicleOverrides={};let unknownVehicles={};
function resetVehicleOverrideForm(){for(const id of ['#vehicleOverrideCallsign','#vehicleOverrideType','#vehicleOverrideStation','#vehicleOverrideDisplay','#vehicleOverrideLabel']){const el=$(id);if(el)el.value=''}setText('#vehicleOverrideFormTitle','Nieuw of fout roepnummer corrigeren');$('#vehicleOverrideCallsign')?.focus()}
function prefillVehicleOverride(callsign){resetVehicleOverrideForm();const u=unknownVehicles[String(callsign)]||{};if($('#vehicleOverrideCallsign'))$('#vehicleOverrideCallsign').value=String(callsign||'');if($('#vehicleOverrideType'))$('#vehicleOverrideType').value=u.suggested_type||'';if($('#vehicleOverrideStation'))$('#vehicleOverrideStation').value=u.suggested_region||u.last_city||'';document.querySelector('#vehicleOverridesCard')?.scrollIntoView({behavior:'smooth',block:'start'})}
function editVehicleOverride(digits){const v=vehicleOverrides[String(digits)]||{};$('#vehicleOverrideCallsign').value=v.callsign||digits;$('#vehicleOverrideType').value=v.type||'';$('#vehicleOverrideStation').value=v.station||'';$('#vehicleOverrideDisplay').value=v.display||'';$('#vehicleOverrideLabel').value=v.label||'';setText('#vehicleOverrideFormTitle',`Override ${v.callsign||digits} aanpassen`);document.querySelector('#vehicleOverridesCard')?.scrollIntoView({behavior:'smooth',block:'start'})}
function renderVehicleOverrides(rows={}){vehicleOverrides=rows||{};const items=Object.entries(vehicleOverrides).sort((a,b)=>String(a[1]?.callsign||a[0]).localeCompare(String(b[1]?.callsign||b[0]),'nl',{numeric:true}));setText('#vehicleOverrideCount',`${items.length} handmatig`);const list=$('#vehicleOverrideList');if(!list)return;list.innerHTML=items.length?items.map(([digits,v])=>`<div class="vehicle-override-row"><div><b>${escapeHtml(v.callsign||digits)}</b><span>${escapeHtml(v.display||v.label||'Brandweervoertuig')}</span><small>${escapeHtml([v.type,v.station].filter(Boolean).join(' • '))}</small></div><div class="vehicle-override-actions"><button type="button" class="secondary-btn" data-override-edit="${escapeHtml(digits)}">Aanpassen</button><button type="button" class="secondary-btn danger-btn" data-override-delete="${escapeHtml(digits)}">Verwijderen</button></div></div>`).join(''):'<div class="unknown-row">Nog geen handmatige correcties.</div>'}
async function loadVehicleOverrides(){try{const d=await api('/api/vehicle-overrides');renderVehicleOverrides(d.overrides?.vehicles||{})}catch(e){setText('#vehicleOverrideCount','fout');$('#vehicleOverrideList').textContent=e.message}}
async function saveVehicleOverride(){const b=$('#saveVehicleOverrideBtn'),payload={callsign:$('#vehicleOverrideCallsign').value,type:$('#vehicleOverrideType').value,station:$('#vehicleOverrideStation').value,display:$('#vehicleOverrideDisplay').value,label:$('#vehicleOverrideLabel').value};b.disabled=true;try{const d=await api('/api/vehicle-overrides/upsert',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});renderVehicleOverrides(d.overrides?.vehicles||{});resetVehicleOverrideForm();await Promise.allSettled([vehicleDb(),unknown()]);flash(`Roepnummer ${d.vehicle?.callsign||payload.callsign} handmatig opgeslagen ✓`,'ok')}catch(e){flash(`Roepnummer opslaan mislukt: ${e.message}`,'error')}finally{b.disabled=false}}
async function deleteVehicleOverride(digits){const v=vehicleOverrides[String(digits)]||{};if(!confirm(`Handmatige correctie voor ${v.callsign||digits} verwijderen? Daarna wordt weer de online database gebruikt.`))return;try{const d=await api('/api/vehicle-overrides/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({digits})});renderVehicleOverrides(d.overrides?.vehicles||{});await Promise.allSettled([vehicleDb(),unknown()]);flash(`Override ${v.callsign||digits} verwijderd ✓`,'ok')}catch(e){flash(`Override verwijderen mislukt: ${e.message}`,'error')}}
async function unknown(){try{const d=await api('/api/unknown-vehicles?limit=30'),rows=d.unknown||[];unknownVehicles=Object.fromEntries(rows.map(x=>[String(x.callsign),x]));$('#unknownList').innerHTML=rows.length?rows.map(x=>`<div class="unknown-row"><div class="unknown-row-head"><b>${escapeHtml(x.callsign)}</b><button type="button" class="secondary-btn mini-btn" data-unknown-callsign="${escapeHtml(x.callsign)}">Suggestie gebruiken</button></div><span>${escapeHtml(x.last_city||'onbekende plaats')}</span>${x.suggested_type||x.suggested_region?`<br><small>Suggestie: ${escapeHtml([x.suggested_type,x.suggested_region].filter(Boolean).join(' • '))}</small>`:''}<br><small>${escapeHtml(x.last_message||'')}</small></div>`).join(''):'<div class="unknown-row">Geen onbekende brandweerroepnummers 🎉</div>'}catch(e){$('#unknownList').textContent=e.message}}
async function vehicleHistory(){const el=$('#vehicleHistoryList');if(!el)return;try{const d=await api('/api/vehicle-history?limit=30'),rows=d.history||[];el.innerHTML=rows.length?rows.map(x=>`<div class="history-row"><b>${escapeHtml(x.callsign||x.digits||'roepnummer')}</b> • ${escapeHtml(x.action||x.reason||'gewijzigd')}<br><small>${escapeHtml(x.at||x.timestamp||'')} ${escapeHtml(x.source||'')}</small></div>`).join(''):'<div class="history-row">Nog geen wijzigingen geregistreerd.</div>'}catch(e){el.textContent=e.message}}
function renderQuickMode(){const mode=String(settings.speechMode||'normal');setText('#quickSpeechMode',mode==='mute'?'STIL':mode==='priority'?'Alleen prioriteit':'Normaal');for(const [id,m] of [['#quickNormalBtn','normal'],['#quickPriorityBtn','priority'],['#quickMuteBtn','mute']])$(id)?.classList.toggle('active',mode===m)}
function renderSupervisor(x={}){const ok=!!x.running||x.state==='healthy'||x.backend_ok===true;setText('#quickSupervisorStatus',x.state|| (ok?'healthy':'offline'));const p=$('#quickSupervisorPill');if(p){p.textContent=ok?'watchdog actief':'watchdog offline';p.className='status-pill '+(ok?'online':'error')}}
async function supervisorStatus(){try{const d=await api('/api/supervisor/status');renderSupervisor(d.supervisor||d)}catch{renderSupervisor({state:'offline'})}}
async function quickDetails(){try{const d=await api('/api/messages?limit=1'),m=(d.messages||[])[0];setText('#quickLastMessage',m?`${m.incident_type||m.title||'Melding'}${m.city?' • '+m.city:''}`.slice(0,90):'nog geen')}catch{setText('#quickLastMessage','niet beschikbaar')}}
async function quickAction(action,payload={}){try{const d=await api('/api/quick-action',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...payload})});if(d.settings){renderSettings(d.settings);settings={...settings,...d.settings}}if(action==='restart-kiosk')flash('Kiosk-herstart aangevraagd ✓','ok');else if(action==='replay-last')flash('Laatste melding opnieuw aangeboden ✓','ok');else if(action==='stop-speech')flash('Geluid gestopt ✓','ok');else flash('Snelactie toegepast ✓','ok');renderQuickMode();return d}catch(e){flash(`Snelactie mislukt: ${e.message}`,'error')}}
let previewTimer=null;async function livePreview(){clearTimeout(previewTimer);previewTimer=setTimeout(async()=>{const raw=$('#testInput')?.value?.trim()||'';if(!raw)return;try{const d=await api('/api/parser/debug',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({raw})}),x=d.parse||{};setText('#previewPriority',`${x.priority||'—'} • ${String(x.service||'overig').toUpperCase()}`);setText('#previewType',x.incident_type||x.type||x.title||'Onbekend incident');setText('#previewLocation',x.location||x.address||'Locatie niet herkend');setText('#previewCity',x.city||'Plaats niet herkend');setText('#previewIncident',`Incident: ${x.incident_key||'—'}`);setText('#previewScale',`Opschaling: ${x.scale||x.scale_label||'—'}`);const units=x.units||x.vehicles||[];setText('#previewVehicle',`Voertuigen: ${Array.isArray(units)?units.length:(units?1:0)}`);setText('#previewSpeech',`Omroep: ${x.speech||x.speech_text||'wordt bij test opgebouwd'}`);const pre=$('#parserDebugDetails');if(pre)pre.textContent=JSON.stringify(x,null,2)}catch(e){setText('#previewType','Parserfout');setText('#previewLocation',e.message)}},220)}
let githubUpdateSettings={github_repo:'xSophie1119/lichtkrant',github_auto_check:true,github_auto_install:true,github_check_minutes:5,github_branch_updates:true,github_branch:'main'};
let githubUpdateStatus={};
function renderGithubUpdateSettings(x={}){
  githubUpdateSettings={...githubUpdateSettings,...x};
  if($('#githubRepoInput'))$('#githubRepoInput').value=githubUpdateSettings.github_repo||'xSophie1119/lichtkrant';
  if($('#githubAutoCheckInput'))$('#githubAutoCheckInput').checked=!!githubUpdateSettings.github_auto_check;
  if($('#githubAutoInstallInput'))$('#githubAutoInstallInput').checked=!!githubUpdateSettings.github_auto_install;
  if($('#githubCheckMinutesInput'))$('#githubCheckMinutesInput').value=String(githubUpdateSettings.github_check_minutes||5);
  if($('#githubBranchUpdatesInput'))$('#githubBranchUpdatesInput').checked=githubUpdateSettings.github_branch_updates!==false;
  if($('#githubBranchInput'))$('#githubBranchInput').value=githubUpdateSettings.github_branch||'main';
}
async function loadGithubUpdateSettings(){try{const d=await api('/api/update/github/settings');renderGithubUpdateSettings(d.settings||{})}catch(e){setText('#updateRepoStatus','instellingen fout');setText('#updateDetail',e.message)}}
function renderUpdateStatus(st={}){
  githubUpdateStatus=st||{};
  setText('#updateCurrentVersion',st.current_version||'—');
  setText('#updateLatestVersion',st.latest_version?`v${st.latest_version}${st.latest_revision?' • '+st.latest_revision.slice(0,7):''}`:'nog niet gecontroleerd');
  setText('#updateRepoStatus',st.github_repo||githubUpdateSettings.github_repo||'niet ingesteld');
  const state=String(st.state||'idle');setText('#updateStateText',state);
  const pill=$('#updateStatusPill');if(pill){const available=!!st.available,err=state==='error';pill.textContent=err?'fout':available?`v${st.latest_version} beschikbaar`:state==='up-to-date'||state==='ready'?'actueel':state;pill.className='status-pill '+(err?'error':available?'':'online')}
  const detail=$('#updateDetail');if(detail){if(st.error){detail.textContent=`Updatefout: ${st.error}`;detail.dataset.kind='error'}else if(st.available){detail.textContent=`${st.message||`Versie ${st.latest_version} beschikbaar`}${st.asset_name?' • '+st.asset_name:''}.`;detail.dataset.kind='ok'}else{detail.textContent=st.message||'GitHub nog niet gecontroleerd.';detail.dataset.kind=''}}
  const install=$('#installUpdateBtn');if(install)install.disabled=!st.available||['downloading','validating','backup','installing','restarting','rollback'].includes(state);
}
async function updateStatus(){try{const d=await api('/api/update/status');renderUpdateStatus(d)}catch(e){setText('#updateStatusPill','offline');setText('#updateDetail',e.message)}}
async function saveUpdateSettings(){const b=$('#saveUpdateSettingsBtn');b.disabled=true;try{const payload={github_repo:($('#githubRepoInput').value||'').trim(),github_auto_check:$('#githubAutoCheckInput').checked,github_auto_install:$('#githubAutoInstallInput').checked,github_check_minutes:Number($('#githubCheckMinutesInput').value)||5,github_branch_updates:$('#githubBranchUpdatesInput').checked,github_branch:($('#githubBranchInput').value||'main').trim()};const d=await api('/api/update/github/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});renderGithubUpdateSettings(d.settings||payload);flash('GitHub update-instellingen opgeslagen ✓','ok');await Promise.allSettled([updateStatus(),loadGithubSettingsSyncConfig()])}catch(e){flash(`Update-instellingen: ${e.message}`,'error')}finally{b.disabled=false}}
async function checkGithubUpdate(install=false){const b=$(install?'#installUpdateBtn':'#checkUpdateBtn');b.disabled=true;b.textContent=install?'Installeren…':'Controleren…';try{const d=await api('/api/update/github/check',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({install}),timeoutMs:install?120000:45000});renderUpdateStatus(d.status||{});if(install){flash('Update gedownload. De monitor maakt een backup en herstart automatisch…','ok');setTimeout(updateStatus,2500)}else{flash(d.status?.available?`Versie ${d.status.latest_version} beschikbaar.`:'Je gebruikt de nieuwste versie ✓',d.status?.available?'':'ok')}}catch(e){flash(`GitHub update: ${e.message}`,'error');await updateStatus()}finally{if(!install){b.disabled=false;b.textContent='Controleer nu'}else{b.textContent='Update installeren'}}}
async function rollbackUpdate(){const b=$('#rollbackUpdateBtn');if(!confirm('Vorige programmaversie herstellen? Config, database en achtergrond blijven behouden.'))return;b.disabled=true;try{const d=await api('/api/update/rollback',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});flash(`Rollback naar ${d.target_version||'vorige versie'} gestart…`,'ok');setTimeout(updateStatus,2500)}catch(e){flash(`Rollback: ${e.message}`,'error');b.disabled=false}}
let githubSettingsSync={github_settings_auto_sync:false,github_settings_path:'p2000-settings.json',github_settings_branch:'main',github_settings_minutes:5};
function renderGithubSettingsSyncConfig(x={}){githubSettingsSync={...githubSettingsSync,...x};$('#githubSettingsAutoSyncInput').checked=!!githubSettingsSync.github_settings_auto_sync;$('#githubSettingsPathInput').value=githubSettingsSync.github_settings_path||'p2000-settings.json';$('#githubSettingsBranchInput').value=githubSettingsSync.github_settings_branch||githubUpdateSettings.github_branch||'main';$('#githubSettingsMinutesInput').value=String(githubSettingsSync.github_settings_minutes||5)}
async function loadGithubSettingsSyncConfig(){try{const d=await api('/api/github/settings-sync/config');renderGithubSettingsSyncConfig(d.config||{})}catch(e){setText('#githubSettingsDetail',`Configuratie laden mislukt: ${e.message}`)}}
function renderGithubSettingsStatus(st={}){const state=String(st.state||'idle'),pill=$('#githubSettingsStatusPill');setText('#githubSettingsState',state);setText('#githubSettingsRevision',st.revision||'—');setText('#githubSettingsCheckedAt',st.updated_at?new Date(st.updated_at).toLocaleString('nl-NL'):'—');setText('#githubSettingsAppliedKeys',Array.isArray(st.applied_keys)?`${st.applied_keys.length} velden`:'—');setText('#githubSettingsDetail',st.error?`Fout: ${st.error}`:(st.message||'Nog niet gecontroleerd.'));if(pill){const err=state==='error';pill.textContent=err?'fout':state==='applied'?'toegepast':state==='up-to-date'?'actueel':state;pill.className='status-pill '+(err?'error':state==='applied'||state==='up-to-date'?'online':'')}}
async function githubSettingsStatus(){try{const d=await api('/api/github/settings-sync/status');renderGithubSettingsStatus(d.status||{})}catch(e){setText('#githubSettingsStatusPill','offline');setText('#githubSettingsDetail',e.message)}}
async function saveGithubSettingsSync(){const b=$('#saveGithubSettingsBtn');b.disabled=true;try{const payload={github_settings_auto_sync:$('#githubSettingsAutoSyncInput').checked,github_settings_path:($('#githubSettingsPathInput').value||'').trim(),github_settings_branch:($('#githubSettingsBranchInput').value||'main').trim(),github_settings_minutes:Number($('#githubSettingsMinutesInput').value)||5};const d=await api('/api/github/settings-sync/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});renderGithubSettingsSyncConfig(d.config||payload);flash('GitHub-instellingensynchronisatie opgeslagen ✓','ok');setTimeout(githubSettingsStatus,900)}catch(e){flash(`Synchronisatie opslaan: ${e.message}`,'error')}finally{b.disabled=false}}
async function pullGithubSettings(){const b=$('#pullGithubSettingsBtn');b.disabled=true;b.textContent='Ophalen…';try{const d=await api('/api/github/settings-sync/pull',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}',timeoutMs:45000});renderGithubSettingsStatus(d.status||{});if(d.settings)renderSettings(d.settings);flash('Instellingen vanaf GitHub toegepast ✓','ok')}catch(e){flash(`GitHub-instellingen: ${e.message}`,'error');await githubSettingsStatus()}finally{b.disabled=false;b.textContent='Nu ophalen en toepassen'}}
async function loadSetup(){try{const d=await api('/api/setup');setupProfile=d.setup||{};const regionMeta=new Map((setupProfile.regions||[]).map(r=>[r.slug,r]));const selected=Object.keys(setupProfile.region_disciplines||{});const tags=selected.map(slug=>regionMeta.get(slug)?.label||slug);$('#scopeTags').innerHTML=tags.map(x=>`<span>${escapeHtml(x)}</span>`).join('')||'<span>Nog niet ingesteld</span>';const owner=setupProfile.profile_type==='bedrijf'?(setupProfile.company_name||'Bedrijf'):(setupProfile.person_name||'Particulier');$('#profileTitle').textContent=(setupProfile.standplaats_city||setupProfile.standplaats)?`Standplaats ${setupProfile.standplaats_city||setupProfile.standplaats}`:'Installatieprofiel';$('#profileSummary').textContent=`${owner} • ${selected.length} regio${selected.length===1?'':'’s'} • ${(setupProfile.feed_urls||[]).length} RSS-bronnen. Wijzig regio’s en disciplines via de Configuratiewizard.`;$('#profileBadge').textContent=setupProfile.profile_type==='bedrijf'?'BEDRIJF':'PARTICULIER';const t=$('#testInput');if(t&&t.dataset.autoExample!=='0'){const place=setupProfile.standplaats_city||setupProfile.standplaats||'Utrecht';t.value=`P 1 BR woning Hoofdstraat ${place}`;t.dataset.autoExample='1';}}catch(e){$('#profileSummary').textContent=`Installatieprofiel laden mislukt: ${e.message}`}}
function renderIdleBuilderPreview(){const box=$('#idleBuilderPreview');if(!box)return;const layout=$('#idleLayoutInput')?.value||settings.idleLayout||'center',headline=($('#idleHeadlineInput')?.value||settings.idleHeadline||settings.name||'P2000 Monitor').trim(),sub=($('#idleSublineInput')?.value||settings.idleSubline||'P2000 MELDINGEN HEBBEN DIRECT VOORRANG').trim(),scale=clamp($('#idleClockScaleInput')?.value||settings.idleClockScale,65,135,100),showName=$('#idleShowNameInput')?.checked!==false,showDate=$('#idleShowDateInput')?.checked!==false,showSeconds=$('#idleShowSecondsInput')?.checked!==false,showStatus=$('#idleShowStatusInput')?.checked!==false,now=new Date();box.dataset.layout=layout;box.querySelector('.idle-preview-name').textContent=showName?(headline||settings.name||'P2000 Monitor'):'';box.querySelector('.idle-preview-time').innerHTML=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}${showSeconds?`<small>${String(now.getSeconds()).padStart(2,'0')}</small>`:''}`;box.querySelector('.idle-preview-time').style.fontSize=`${Math.round(2.45*scale/100)}rem`;box.querySelector('.idle-preview-date').textContent=showDate?now.toLocaleDateString('nl-NL',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).toUpperCase():'';box.querySelector('.idle-preview-status').textContent=showStatus?sub:'';}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function init(){
  initTuneSelects();updateTuneVolumeLabel();$('#masterVolumeInput')?.addEventListener('input',e=>syncVolumeControls(e.target.value));$('#quickVolumeInput')?.addEventListener('input',e=>scheduleQuickVolume(e.target.value));$('#quickVolumeInput')?.addEventListener('change',e=>scheduleQuickVolume(e.target.value,{immediate:true}));$('#quickNormalBtn')?.addEventListener('click',()=>quickAction('speech-normal'));$('#quickPriorityBtn')?.addEventListener('click',()=>quickAction('speech-priority'));$('#quickMuteBtn')?.addEventListener('click',()=>quickAction('speech-mute'));$('#quickReplayBtn')?.addEventListener('click',()=>quickAction('replay-last',{speak:true}));$('#quickStopBtn')?.addEventListener('click',()=>quickAction('stop-speech'));$('#quickTuneTestBtn')?.addEventListener('click',testDispatchTune);$('#quickVoiceTestBtn')?.addEventListener('click',voiceTest);$('#quickDisplayOnBtn')?.addEventListener('click',()=>displayPower('on'));$('#quickDisplayOffBtn')?.addEventListener('click',()=>displayPower('off'));$('#quickRestartKioskBtn')?.addEventListener('click',()=>quickAction('restart-kiosk'));$('#quickRestartBackendBtn')?.addEventListener('click',()=>quickAction('restart-backend'));$('#testInput')?.addEventListener('input',livePreview);for(const id of ['#idleLayoutInput','#idleHeadlineInput','#idleSublineInput','#idleShowNameInput','#idleShowDateInput','#idleShowSecondsInput','#idleShowStatusInput','#idleClockScaleInput'])$(id)?.addEventListener('input',()=>{setText('#idleClockScaleValue',Math.round(clamp($('#idleClockScaleInput')?.value,65,135,100)));renderIdleBuilderPreview()});save112NuToggle();
  $('#saveBtn').addEventListener('click',save);$('#dispatchTuneVolumeInput')?.addEventListener('input',()=>{updateTuneVolumeLabel();scheduleTuneSave()});for(const id of ['#dispatchTuneEnabledInput','#dispatchTuneDefaultInput','#dispatchTuneBrandweerInput','#dispatchTuneAmbulanceInput','#dispatchTunePolitieInput','#dispatchTuneLifelinerInput','#dispatchTuneKnrmInput','#dispatchTuneUrgentInput','#dispatchTuneYoutubeUrlInput','#dispatchTuneYoutubeSecondsInput'])$(id)?.addEventListener('change',scheduleTuneSave);$('#saveTuneSettingsBtn')?.addEventListener('click',()=>saveTuneSettings());$('#uploadDispatchTuneBtn')?.addEventListener('click',uploadDispatchTune);$('#removeDispatchTuneBtn')?.addEventListener('click',removeDispatchTune);$('#testDispatchTuneBtn')?.addEventListener('click',testDispatchTune);$('#backgroundStyleInput').addEventListener('change',toggleBackgroundColor);$('#uploadBackgroundPhotoBtn')?.addEventListener('click',uploadBackgroundPhoto);$('#removeBackgroundPhotoBtn')?.addEventListener('click',removeBackgroundPhoto);$('#reconnectBtn').addEventListener('click',reconnect);$('#detectDisplayBtn').addEventListener('click',()=>displayInfo().catch(()=>{}));$('#kioskMonitorInput')?.addEventListener('change',applyDisplaySelection);$('#applyDisplayBtn')?.addEventListener('click',applyDisplaySelection);$('#displayOffBtn').addEventListener('click',()=>displayPower('off'));$('#displayOnBtn').addEventListener('click',()=>displayPower('on'));$('#testDisplayBtn').addEventListener('click',()=>testMessage(false));$('#testSpeakBtn').addEventListener('click',()=>testMessage(true));$('#voiceTestBtn').addEventListener('click',voiceTest);$('#stopSpeechBtn').addEventListener('click',stopSpeech);$('#refreshUnknownBtn').addEventListener('click',unknown);$('#syncVehiclesBtn').addEventListener('click',syncVehicles);$('#saveSwApiKeyBtn')?.addEventListener('click',saveSwApiKey);$('#clearSwApiKeyBtn')?.addEventListener('click',clearSwApiKey);$('#saveVehicleOverrideBtn')?.addEventListener('click',saveVehicleOverride);$('#resetVehicleOverrideBtn')?.addEventListener('click',resetVehicleOverrideForm);$('#vehicleOverrideList')?.addEventListener('click',e=>{const edit=e.target.closest('[data-override-edit]'),del=e.target.closest('[data-override-delete]');if(edit)editVehicleOverride(edit.dataset.overrideEdit);if(del)deleteVehicleOverride(del.dataset.overrideDelete)});$('#unknownList')?.addEventListener('click',e=>{const b=e.target.closest('[data-unknown-callsign]');if(b)prefillVehicleOverride(b.dataset.unknownCallsign)});$('#saveUpdateSettingsBtn')?.addEventListener('click',saveUpdateSettings);$('#checkUpdateBtn')?.addEventListener('click',()=>checkGithubUpdate(false));$('#installUpdateBtn')?.addEventListener('click',()=>checkGithubUpdate(true));$('#rollbackUpdateBtn')?.addEventListener('click',rollbackUpdate);$('#saveGithubSettingsBtn')?.addEventListener('click',saveGithubSettingsSync);$('#pullGithubSettingsBtn')?.addEventListener('click',pullGithubSettings);
  Promise.allSettled([loadSetup(),loadSettings(),loadGithubUpdateSettings(),updateStatus(),loadGithubSettingsSyncConfig(),githubSettingsStatus(),status(),feeds(),displayInfo(),tts(),loadSwApiConfig(),vehicleDb(),loadVehicleOverrides(),unknown(),vehicleHistory(),supervisorStatus(),quickDetails()]).then(livePreview);setInterval(status,15000);setInterval(supervisorStatus,15000);setInterval(quickDetails,15000);setInterval(feeds,30000);setInterval(updateStatus,30000);setInterval(githubSettingsStatus,30000);setInterval(unknown,30000);setInterval(tts,30000);setInterval(vehicleDb,60000);
}
init();
