(async function(){
'use strict';
const $=s=>document.querySelector(s),E=window.P2000StudioEngine,base='/api/remote/studio/';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clone=x=>JSON.parse(JSON.stringify(x));const uid=()=>globalThis.crypto?.randomUUID?.()||Date.now().toString(36)+Math.random().toString(36).slice(2);
let design,draft,settings={},dirty=false,logRows=[],correctionPreview=null,recording=null,playIndex=0,playTimer=null,speechText='',currentTab='areas';
function notice(msg,error=false){$('#notice').textContent=msg;$('#notice').classList.toggle('bad',error)}
async function api(path,payload){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const r=await fetch(path.startsWith('/')?path:base+path,{cache:'no-store',signal:controller.signal,...(payload===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)})});const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||'Verzoek mislukt');return d}finally{clearTimeout(timer)}}
function bind(id,fn){$(id).addEventListener('click',async e=>{const b=e.currentTarget;b.disabled=true;try{await fn(e)}catch(err){notice(err.message,true)}finally{b.disabled=b.id==='saveCorrection'?!correctionPreview:false}})}
function changed(){dirty=true;$('#saveState').textContent='Nog niet toegepast';try{sessionStorage.setItem('p2000StudioDraft',JSON.stringify({revision:design.revision,config:draft}))}catch{}}
function chooseTab(name){currentTab=name;document.querySelectorAll('.tab').forEach(el=>el.hidden=el.id!==name);document.querySelectorAll('[data-tab]').forEach(el=>el.setAttribute('aria-selected',String(el.dataset.tab===name)));if(name==='areas')drawMap();if(name==='layout')drawLayout();if(name==='replay')loadRecordings().catch(e=>notice(e.message,true));history.replaceState(null,'','#'+name)}
function options(values,value){return values.map(v=>{const [key,label]=Array.isArray(v)?v:[v,v];return `<option value="${esc(key)}" ${String(key)===String(value)?'selected':''}>${esc(label)}</option>`}).join('')}
function render(){
 $('#rulesEnabled').checked=draft.enabled;$('#defaultAction').value=draft.default_action;$('#unknownLocation').value=draft.unknown_location;
 $('#speechEnabled').checked=draft.speech.enabled;$('#speechCue').checked=draft.speech.cue;$('#speechTemplate').value=draft.speech.template;
 $('#layoutEnabled').checked=draft.layout.enabled;$('#aspect').value=draft.layout.aspect;$('#minFont').value=draft.layout.min_font;
 renderZones();renderRules();renderCorrections();renderBlocks();drawLayout();
}
for(const button of document.querySelectorAll('[data-tab]'))button.addEventListener('click',()=>chooseTab(button.dataset.tab));
bind('#reloadDesign',async()=>{if(dirty&&!window.confirm('Je niet-toegepaste ontwerp vervangen door de opgeslagen versie?'))return;design=await api('config');draft=clone(design.config);dirty=false;sessionStorage.removeItem('p2000StudioDraft');$('#saveState').textContent='Opgeslagen · versie '+design.revision;render();notice('Opgeslagen versie geladen.');});
bind('#save',async()=>{const validated=await api('validate',{config:draft});const saved=await api('config',{config:validated.config,revision:design.revision});design=saved;draft=clone(saved.config);dirty=false;sessionStorage.removeItem('p2000StudioDraft');$('#saveState').textContent='Toegepast · versie '+saved.revision;notice('Je ontwerp is opgeslagen en naar de verbonden schermen gestuurd.');render()});
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
for(const [id,key] of [['#rulesEnabled','enabled'],['#defaultAction','default_action'],['#unknownLocation','unknown_location']])$(id).addEventListener('change',e=>{draft[key]=e.target.type==='checkbox'?e.target.checked:e.target.value;changed()});
// Mercator canvas, same PDOK base layer as the existing incident map. No CDN scripts.
let center={lat:51.56,lon:5.08},zoom=10,points=[],panMode=false,drag=null,editingZone=null;
const project=(lat,lon)=>{const size=256*2**zoom,s=Math.sin(lat*Math.PI/180);return {x:(lon+180)/360*size,y:(.5-Math.log((1+s)/(1-s))/(4*Math.PI))*size}};
const unproject=(x,y)=>{const size=256*2**zoom;return [Math.atan(Math.sinh(Math.PI*(1-2*y/size)))*180/Math.PI,x/size*360-180]};
function mapPoint(e){const rect=$('#areaMap').getBoundingClientRect(),c=project(center.lat,center.lon);return unproject(c.x+e.clientX-rect.left-rect.width/2,c.y+e.clientY-rect.top-rect.height/2)}
function drawMap(){if(!draft)return;const map=$('#areaMap'),w=map.clientWidth||700,h=map.clientHeight||430,c=project(center.lat,center.lon),tiles=$('#tiles');tiles.replaceChildren();let loaded=0,failed=0,total=0;
 for(let y=Math.floor((c.y-h/2)/256);y<=Math.floor((c.y+h/2)/256);y++)for(let x=Math.floor((c.x-w/2)/256);x<=Math.floor((c.x+w/2)/256);x++){
  if(y<0||y>=2**zoom)continue;total++;const img=new Image();img.alt='';img.draggable=false;img.referrerPolicy='no-referrer';img.style.left=(x*256-c.x+w/2)+'px';img.style.top=(y*256-c.y+h/2)+'px';img.onload=()=>{loaded++;$('#mapStatus').textContent=`${points.length} punten · ${panMode?'Sleep om de kaart te verplaatsen':'Tik op de kaart om een hoek toe te voegen'}`};img.onerror=()=>{failed++;if(failed===total&&!loaded)$('#mapStatus').textContent='Kaarttegels niet bereikbaar. Bestaande gebieden blijven bewaard; probeer later opnieuw.'};img.src=`https://service.pdok.nl/brt/achtergrondkaart/wmts/v2_0/grijs/EPSG:3857/${zoom}/${((x%2**zoom)+2**zoom)%2**zoom}/${y}.png`;tiles.append(img);
 }
 drawPolygons();
}
function drawPolygons(){const svg=$('#polygons'),w=$('#areaMap').clientWidth||700,h=$('#areaMap').clientHeight||430,c=project(center.lat,center.lon);svg.setAttribute('viewBox',`0 0 ${w} ${h}`);svg.replaceChildren();
 const sets=[...(draft.zones||[]).filter(z=>z.id!==editingZone).map(z=>({points:z.points,name:z.name,color:z.enabled?'#61eac4':'#778895'})),{points,name:'Nieuw gebied',color:'#ffdc7e'}];
 for(const set of sets){if(!set.points.length)continue;const poly=document.createElementNS('http://www.w3.org/2000/svg','polygon');poly.setAttribute('points',set.points.map(([lat,lon])=>{const p=project(lat,lon);return `${p.x-c.x+w/2},${p.y-c.y+h/2}`}).join(' '));poly.setAttribute('fill',set.color+'33');poly.setAttribute('stroke',set.color);poly.setAttribute('stroke-width','2');const title=document.createElementNS('http://www.w3.org/2000/svg','title');title.textContent=set.name;poly.append(title);svg.append(poly)}
 for(const [lat,lon] of points){const p=project(lat,lon),dot=document.createElementNS('http://www.w3.org/2000/svg','circle');dot.setAttribute('cx',p.x-c.x+w/2);dot.setAttribute('cy',p.y-c.y+h/2);dot.setAttribute('r',5);dot.setAttribute('fill','#ffdc7e');svg.append(dot)}
 $('#mapStatus').textContent=`${points.length} punten · ${panMode?'Sleep om de kaart te verplaatsen':'Tik op de kaart om een hoek toe te voegen'}`;
}
$('#areaMap').addEventListener('pointerdown',e=>{if(e.target.closest('button,a'))return;drag={x:e.clientX,y:e.clientY,c:project(center.lat,center.lon)};$('#areaMap').setPointerCapture?.(e.pointerId)});
$('#areaMap').addEventListener('pointermove',e=>{if(!drag||!panMode)return;const [lat,lon]=unproject(drag.c.x-e.clientX+drag.x,drag.c.y-e.clientY+drag.y);center={lat:Math.max(-80,Math.min(80,lat)),lon:Math.max(-180,Math.min(180,lon))};$('#tiles').style.transform=`translate(${e.clientX-drag.x}px,${e.clientY-drag.y}px)`;drawPolygons()});
$('#areaMap').addEventListener('pointerup',e=>{if(!drag)return;if(!panMode&&Math.hypot(e.clientX-drag.x,e.clientY-drag.y)<12){if(points.length<80)points.push(mapPoint(e));drawPolygons()}if(panMode){$('#tiles').style.transform='';drawMap()}drag=null});$('#areaMap').addEventListener('pointercancel',()=>drag=null);
bind('#zoomIn',()=>{zoom=Math.min(17,zoom+1);drawMap()});bind('#zoomOut',()=>{zoom=Math.max(6,zoom-1);drawMap()});bind('#mapMode',()=>{panMode=!panMode;$('#mapMode').textContent=panMode?'Tekenen':'Verplaatsen';drawPolygons()});
bind('#findPlace',async()=>{const city=$('#mapSearch').value.trim();if(!city)return;const d=await api('/api/geocode?city='+encodeURIComponent(city)+'&zoom=12');if(!d.map)throw new Error('Plaats niet gevonden');center={lat:d.map.lat,lon:d.map.lon};zoom=12;drawMap()});
bind('#undoPoint',()=>{points.pop();drawPolygons()});bind('#clearPoints',()=>{points=[];editingZone=null;$('#zoneName').value='';$('#zoneExpires').value='';drawPolygons()});
bind('#finishZone',async()=>{const name=$('#zoneName').value.trim();if(!name||points.length<3)throw new Error('Geef het gebied een naam en teken minstens drie punten.');const expires=$('#zoneExpires').value?new Date($('#zoneExpires').value).getTime():0;if(expires&&expires<=Date.now())throw new Error('Kies een eindtijd in de toekomst.');const z={id:editingZone||uid(),name,points:clone(points),enabled:true,expires};const candidate=clone(draft);candidate.zones=candidate.zones.filter(x=>x.id!==z.id);candidate.zones.push(z);await api('validate',{config:candidate});draft=candidate;points=[];editingZone=null;$('#zoneName').value='';changed();renderZones();renderRules();drawMap()});
function renderZones(){ $('#zoneList').innerHTML=draft.zones.map(z=>`<div class="record"><strong>${esc(z.name)}</strong><p>${z.points.length} hoeken${z.expires?' · Tot '+esc(new Date(z.expires).toLocaleString('nl-NL')):''}</p><div class="row"><button data-zone-toggle="${esc(z.id)}">${z.enabled?'Uitzetten':'Aanzetten'}</button><button data-zone-edit="${esc(z.id)}">Vorm aanpassen</button><button data-zone-remove="${esc(z.id)}">Verwijderen</button></div></div>`).join('')||'<p>Nog geen gebieden getekend.</p>'}
$('#zoneList').addEventListener('click',e=>{const t=e.target.closest('button');if(!t)return;let z=draft.zones.find(z=>z.id===(t.dataset.zoneToggle||t.dataset.zoneEdit||t.dataset.zoneRemove));if(!z)return;if(t.dataset.zoneRemove){if(draft.rules.some(r=>r.when.zone===z.id)){notice('Dit gebied wordt nog gebruikt in een regel. Pas die regel eerst aan.',true);return}draft.zones=draft.zones.filter(x=>x.id!==z.id)}else if(t.dataset.zoneEdit){editingZone=z.id;points=clone(z.points);center={lat:points[0][0],lon:points[0][1]};$('#zoneName').value=z.name;$('#zoneExpires').value=z.expires?localDate(z.expires):'';drawMap();return}else z.enabled=!z.enabled;changed();renderZones();drawMap();renderRules()});
// Rule precedence is explicit and identical to the live engine.
const services=[['','Elke dienst'],'brandweer','ambulance','politie','lifeliner','knrm','overig'];
function renderRules(){ $('#ruleList').innerHTML=draft.rules.map((r,i)=>`<article class="rule" data-rule="${esc(r.id)}"><div class="heading"><strong>${i+1}. ${esc(r.name)}</strong><div><button data-up aria-label="Regel omhoog">↑</button> <button data-down aria-label="Regel omlaag">↓</button> <button data-delete aria-label="Regel verwijderen">×</button></div></div><label class="check"><input data-key="enabled" type="checkbox" ${r.enabled?'checked':''}>Regel actief</label><label>Naam<input data-key="name" value="${esc(r.name)}" maxlength="100"></label><div class="row"><label>Dienst<select data-when="service">${options(services,r.when.service||'')}</select></label><label>Prioriteit<select data-when="priority">${options([['','Elke prioriteit'],'P1','P2','P3','A0','A1','A2','B1','B2'],r.when.priority||'')}</select></label><label>Bijzondere inzet<select data-when="resource">${options([['','Elke inzet'],['mmt','MMT / Lifeliner'],['ovdg','OvDG']],r.when.resource||'')}</select></label></div><div class="row"><label>Plaats (exact)<input data-when="city" value="${esc(r.when.city||'')}" maxlength="120"></label><label>Tekst bevat<input data-when="contains" value="${esc(r.when.contains||'')}" maxlength="160"></label><label>Gebied<select data-when="zone">${options([['','Elk gebied'],...draft.zones.map(z=>[z.id,z.name])],r.when.zone||'')}</select></label></div><div class="row"><label>Minimale opschaling<select data-when="min_scale">${options([['','Geen eis'],[50,'Middel'],[60,'Groot'],[70,'Zeer groot']],r.when.min_scale??'')}</select></label><label>Dan<select data-key="action">${options([['show','Tonen + normale omroep'],['hide','Verbergen'],['silent','Tonen zonder omroep'],['urgent','Tonen met voorrang']],r.action)}</select></label><label>Attentietoon<select data-key="cue">${options([['auto','Bestaande tooninstellingen'],['none','Geen toon'],'brandweer','politie','ambulance','lifeliner'],r.cue)}</select></label></div></article>`).join('')||'<p>Nog geen regels. Voeg je eerste regel toe.</p>'}
bind('#addRule',()=>{draft.rules.push({id:uid(),name:'Nieuwe regel',enabled:true,when:{},action:'show',cue:'auto'});changed();renderRules()});
$('#ruleList').addEventListener('change',e=>{const card=e.target.closest('[data-rule]'),r=draft.rules.find(x=>x.id===card?.dataset.rule);if(!r)return;const k=e.target.dataset.when;if(k){if(e.target.value==='')delete r.when[k];else r.when[k]=k==='min_scale'?Number(e.target.value):e.target.value}else if(e.target.dataset.key)r[e.target.dataset.key]=e.target.type==='checkbox'?e.target.checked:e.target.value;changed()});
$('#ruleList').addEventListener('click',e=>{const b=e.target.closest('button'),card=b?.closest('[data-rule]');if(!card)return;const i=draft.rules.findIndex(x=>x.id===card.dataset.rule);if(b.hasAttribute('data-delete'))draft.rules.splice(i,1);else{const to=i+(b.hasAttribute('data-up')?-1:1);if(to<0||to>=draft.rules.length)return;[draft.rules[i],draft.rules[to]]=[draft.rules[to],draft.rules[i]]}changed();renderRules()});
async function parse(raw){return (await api('parse',{raw})).message}
async function locate(m){if(!m.city||!m.location)return null;try{const d=await api('/api/geocode?city='+encodeURIComponent(m.city)+'&location='+encodeURIComponent(m.location));return d.map&&d.map.confidence>=.8?{lat:d.map.lat,lon:d.map.lon,source:d.map.source}:null}catch{return null}}
function explain(d){return `<p class="badge">${d.show?'TONEN':'VERBERGEN'}${d.speak===false?' · GEEN OMROEP':''}</p><p>${esc(d.reason)}</p>${d.matches?.length?'<ol>'+d.matches.map(r=>`<li>${esc(r.name)}: ${r.match===null?'locatie onbekend':r.match?'past':'past niet'}${r.match&&r.name!==d.rule?' · lagere voorrang':''}</li>`).join('')+'</ol>':''}`}
bind('#testRule',async()=>{const m=await parse($('#ruleRaw').value),geo=await locate(m),d=E.decision(draft,m,geo,settings);$('#ruleResult').innerHTML=explain(d)+`<p>Herkend: ${esc(m.service)} · ${esc(m.city)} · ${esc(m.location)}</p><p class="muted">Voorbeeld van de schermregels. Bronselectie en ouderdom kunnen een live melding daarnaast tegenhouden.</p>`});
bind('#testBatch',async()=>{const rows=(await api('records')).records;let show=0,hide=0,unknown=0;for(const r of rows){const m=r.message.corrected||r.message,geo=r.decisions.find(x=>x.geo)?.geo;const d=E.decision(draft,m,geo,settings);if(d.show)show++;else hide++;if(d.unknown)unknown++}$('#ruleResult').innerHTML=`<p>${rows.length} meldingen gecontroleerd: <b>${show} tonen</b>, <b>${hide} verbergen</b>. Bij ${unknown} meldingen is de locatie onbekend.</p><p class="muted">Dit is de uitkomst van je ontwerp, vóór bron-, ouderdoms- en duplicaatcontroles. Gebruikt bewaarde coördinaten; doet geen grote reeks kaartzoekopdrachten.</p>`});
// Actual recorder data, including the source gate and each reporting display.
async function loadLog(more=false){const before=more?logRows.at(-1)?.seq:0;const d=await api('records?q='+encodeURIComponent($('#logSearch').value)+(before?'&before='+before:''));logRows=more?[...logRows,...d.records]:d.records;$('#moreLog').hidden=d.records.length<100;$('#logList').innerHTML=logRows.map(r=>`<article class="record"><span class="badge">${!r.scope?'BRONFILTER':r.decisions.length?(r.decisions[0].shown?'DOORGEGEVEN AAN SCHERM':'NIET GETOOND'):'ONTVANGEN'}</span><h3>${esc(r.message.title)}</h3><p>${esc(new Date(r.at*1000).toLocaleString('nl-NL'))} · ${esc(r.message.source)}<br>${esc(!r.scope?'Niet toegelaten door regio-/disciplinekeuze van de bron':r.decisions[0]?.reason||'Nog geen schermbeslissing ontvangen')}</p><button data-record="${r.seq}">Bekijk herkenning & uitleg</button></article>`).join('')||'<p>Nog geen meldingen opgenomen. Het log begint na installatie van deze versie.</p>';if(d.error)notice(d.error,true)}
bind('#refreshLog',()=>loadLog());bind('#searchLog',()=>loadLog());bind('#moreLog',()=>loadLog(true));
$('#logList').addEventListener('click',e=>{const b=e.target.closest('[data-record]');if(!b)return;const r=logRows.find(x=>x.seq===Number(b.dataset.record));if(!r)return;const m=r.message.corrected||r.message;$('#logDetail').innerHTML=`<div class="card"><h3>Van bron tot scherm</h3><p>${esc(r.message.title)}</p><table><tbody>${['service','priority','city','location','units','parser_notes'].map(k=>`<tr><th>${esc(k)}</th><td>${esc(Array.isArray(m[k])?m[k].join(', '):m[k])}</td></tr>`).join('')}</tbody></table><h4>Schermbeslissingen</h4>${r.decisions.map(d=>`<p><b>${esc(d.client_id)}</b> · ${esc(d.reason)} · ontwerp ${d.revision}</p>`).join('')||'<p>Geen schermbeslissing ontvangen. Er kan geen scherm verbonden zijn, of de melding is bij opstarten als geschiedenis geladen.</p>'}<div class="row"><button id="correctSelected">Herkenning corrigeren</button><button id="ruleSelected">In regelbouwer proberen</button></div><p><a href="/setup.html?edit=1">Bronselectie wijzigen</a> · <a href="/control">Schermfilters en tijdinstellingen</a></p></div>`;bind('#correctSelected',()=>{$('#correctionRaw').value=r.message.title;correctionPreview=null;$('#saveCorrection').disabled=true;chooseTab('corrections')});bind('#ruleSelected',()=>{$('#ruleRaw').value=r.message.title;chooseTab('rules')});$('#logDetail').scrollIntoView?.({behavior:'smooth'})});
// Speech preview calls the actual lightkrant functions in an inert frame.
for(const k of ['incident','where','city','location','priority','scale','units','service']){const b=document.createElement('button');b.textContent='{'+k+'}';b.addEventListener('click',()=>{const t=$('#speechTemplate'),start=t.selectionStart,end=t.selectionEnd;t.value=t.value.slice(0,start)+'{'+k+'}'+t.value.slice(end);draft.speech.template=t.value;changed();t.focus();t.setSelectionRange(start+k.length+2,start+k.length+2)});$('#speechChips').append(b)}
$('#speechTemplate').addEventListener('input',e=>{draft.speech.template=e.target.value;speechText='';$('#speechListen').disabled=true;changed()});for(const [id,key] of [['#speechEnabled','enabled'],['#speechCue','cue']])$(id).addEventListener('change',e=>{draft.speech[key]=e.target.checked;changed()});
async function exactSpeech(m,d=draft,s=settings){const frame=$('#speechFrame');if(!frame.contentWindow?.P2000SpeechPreview)await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Omroepvoorbeeld kon niet laden')),10000);frame.addEventListener('load',()=>{clearTimeout(timer);resolve()},{once:true})});const engine=frame.contentWindow.P2000SpeechPreview;if(!engine)throw new Error('Omroepvoorbeeld ontbreekt');await engine.loadVehicles();return engine.format(m,{revision:design.revision,config:d},s)}
bind('#speechPreview',async()=>{const m=await parse($('#speechRaw').value);speechText=await exactSpeech(m);$('#speechText').textContent=speechText||'Deze melding levert geen omroeptekst op.';$('#speechListen').disabled=!speechText});
bind('#speechListen',()=>{if(!window.speechSynthesis)throw new Error('Deze browser ondersteunt geen luistervoorbeeld');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(speechText);u.lang='nl-NL';u.rate=Number(settings.speechRate)||.96;u.onerror=()=>notice('Het luistervoorbeeld kon niet worden afgespeeld.',true);speechSynthesis.speak(u)});bind('#speechStop',()=>window.speechSynthesis?.cancel());
$('#speechRaw').addEventListener('input',()=>{speechText='';$('#speechListen').disabled=true});
// Corrections always show impact before saving; changing inputs invalidates the preview.
for(const el of $('#corrections').querySelectorAll('input,textarea,select'))el.addEventListener('input',()=>{correctionPreview=null;$('#saveCorrection').disabled=true});
function correctionInput(){const field=$('#correctionField').value,value=$('#correctionValue').value.trim(),mode=$('#correctionMode').value;return {id:uid(),mode,match:mode==='exact'?$('#correctionRaw').value:$('#correctionMatch').value,changes:{[field]:field==='units'?value.split(',').map(x=>x.trim()).filter(Boolean):value}}}
bind('#previewCorrection',async()=>{const data=await api('correction-preview',{raw:$('#correctionRaw').value,correction:correctionInput()});correctionPreview={data,raw:$('#correctionRaw').value};$('#correctionEffect').innerHTML=`<p>${data.affected.length} gewijzigde meldingen in de laatste ${data.checked} ontvangen meldingen.</p><h4>Dit voorbeeld</h4><pre>${esc(JSON.stringify({voor:Object.fromEntries(Object.keys(data.correction.changes).map(k=>[k,data.before[k]])),na:Object.fromEntries(Object.keys(data.correction.changes).map(k=>[k,data.after[k]]))},null,2))}</pre><details><summary>Andere getroffen meldingen bekijken</summary>${data.affected.map(x=>`<p>${esc(x.raw)}</p><pre>${esc(JSON.stringify(x.diff,null,2))}</pre>`).join('')||'<p>Geen andere recente meldingen veranderen.</p>'}</details>`;$('#saveCorrection').disabled=false});
function acceptCorrection(result){design=result;draft.corrections=clone(result.config.corrections);draft.examples=clone(result.config.examples);correctionPreview=null;$('#saveCorrection').disabled=true;renderCorrections();if(dirty)changed();else $('#saveState').textContent='Toegepast · versie '+design.revision}
bind('#saveCorrection',async()=>{if(!correctionPreview)throw new Error('Bekijk eerst een voorvertoning.');const {data,raw}=correctionPreview;const result=await api('correction-save',{raw,correction:data.correction,revision:data.revision,preview_revision:data.revision});acceptCorrection(result);notice('Correctie en testvoorbeeld zijn bewaard. Nieuwe ontvangsten gebruiken de correctie.');$('#saveCorrection').disabled=true});
function renderCorrections(){$('#correctionList').innerHTML=draft.corrections.map(c=>`<div class="record"><b>${c.mode==='exact'?'Exact':'Bevat'}: ${esc(c.match)}</b><pre>${esc(JSON.stringify(c.changes,null,2))}</pre><button data-remove-correction="${esc(c.id)}">Correctie verwijderen</button></div>`).join('')||'<p>Nog geen eigen correcties.</p>'}
$('#correctionList').addEventListener('click',async e=>{const b=e.target.closest('[data-remove-correction]');if(!b)return;try{acceptCorrection(await api('correction-delete',{id:b.dataset.removeCorrection,revision:design.revision}));notice('Correctie verwijderd. Het testvoorbeeld blijft bewaard om het effect te controleren.')}catch(err){notice(err.message,true)}});
bind('#runExamples',async()=>{const d=await api('examples');$('#exampleResults').innerHTML=d.tests.map(t=>`<div class="record"><span class="badge ${t.passed?'':'bad'}">${t.passed?'GESLAAGD':'AFWIJKING'}</span><p>${esc(t.raw)}</p><pre>${esc(JSON.stringify({verwacht:t.expected,gevonden:t.actual},null,2))}</pre>${t.parser_already_correct?'<p>De parser herkent dit inmiddels ook zonder de lokale correctie.</p>':''}</div>`).join('')||'<p>Bewaar een correctie om het eerste testvoorbeeld toe te voegen.</p>'});
// One canvas renderer for the physical screen, design preview and isolated player.
const names={message:'Melding',map:'Kaart',vehicles:'Voertuigen',clock:'Klok',incidents:'Incidentoverzicht'};
const sample={id:'example',title:'Brand in een woning',priority:'P1',city:'Tilburg',location:'Voorbeeldstraat',service:'brandweer',vehicle_labels:['Tankautospuit Tilburg Vossenberg','Hoogwerker Tilburg Centrum']};
const currentBoxes=()=>draft.layout.scenes[$('#scene').value];
function renderBlocks(){$('#blockList').innerHTML=currentBoxes().map((b,i)=>`<div class="block-row"><div class="heading"><strong>${names[b.type]}</strong><button data-remove-block="${i}">Verwijderen</button></div><div class="row">${[['x','Links %'],['y','Boven %'],['w','Breedte %'],['h','Hoogte %']].map(([k,label])=>`<label>${label}<input data-box="${i}" data-dimension="${k}" type="number" min="${k==='x'||k==='y'?0:5}" max="100" step="1" value="${b[k]}"></label>`).join('')}</div></div>`).join('')}
function drawLayout(){if(!draft)return;const [w,h]=draft.layout.aspect.split(':').map(Number),canvas=$('#layoutCanvas');canvas.width=1920;canvas.height=Math.round(1920*h/w);$('#designStage').style.aspectRatio=`${w}/${h}`;const which=$('#scene').value,ms=which==='idle'?[]:which==='single'?[sample]:[sample,{...sample,id:'other',city:'Waalwijk',location:'Andere straat'}];const warns=E.draw(canvas,draft.layout,{message:ms[0],messages:ms,preview:true});$('#layoutWarnings').textContent=warns.join(' · ')||'Alle voorbeeldtekst past in de gekozen blokken.';$('#blockHandles').innerHTML=currentBoxes().map((b,i)=>`<button class="handle" data-handle="${i}" aria-label="${names[b.type]} verplaatsen" style="left:${b.x}%;top:${b.y}%;width:${b.w}%;height:${b.h}%">${names[b.type]}</button>`).join('')}
$('#scene').addEventListener('change',()=>{renderBlocks();drawLayout()});for(const [id,key] of [['#layoutEnabled','enabled'],['#aspect','aspect'],['#minFont','min_font']])$(id).addEventListener('change',e=>{draft.layout[key]=e.target.type==='checkbox'?e.target.checked:e.target.type==='number'?Number(e.target.value):e.target.value;changed();drawLayout()});
bind('#addBlock',()=>{const type=$('#blockType').value;if(currentBoxes().some(b=>b.type===type))throw new Error('Dit blok staat al in deze situatie.');currentBoxes().push({type,x:5,y:5,w:40,h:30});changed();renderBlocks();drawLayout()});
$('#blockList').addEventListener('change',e=>{if(!e.target.dataset.dimension)return;const b=currentBoxes()[Number(e.target.dataset.box)],k=e.target.dataset.dimension,n=Number(e.target.value);b[k]=Math.min(100,Math.max(k==='x'||k==='y'?0:5,n));b.x=Math.min(b.x,100-b.w);b.y=Math.min(b.y,100-b.h);changed();renderBlocks();drawLayout()});$('#blockList').addEventListener('click',e=>{const b=e.target.closest('[data-remove-block]');if(!b)return;currentBoxes().splice(Number(b.dataset.removeBlock),1);changed();renderBlocks();drawLayout()});
let boxDrag=null;$('#blockHandles').addEventListener('pointerdown',e=>{const b=e.target.closest('[data-handle]');if(!b)return;const index=Number(b.dataset.handle),box=currentBoxes()[index];boxDrag={index,x:e.clientX,y:e.clientY,bx:box.x,by:box.y,el:b};b.setPointerCapture?.(e.pointerId)});$('#blockHandles').addEventListener('pointermove',e=>{if(!boxDrag)return;const rect=$('#designStage').getBoundingClientRect(),b=currentBoxes()[boxDrag.index];b.x=Math.min(100-b.w,Math.round(Math.max(0,boxDrag.bx+(e.clientX-boxDrag.x)/rect.width*100)));b.y=Math.min(100-b.h,Math.round(Math.max(0,boxDrag.by+(e.clientY-boxDrag.y)/rect.height*100)));boxDrag.el.style.left=b.x+'%';boxDrag.el.style.top=b.y+'%'});function endDrag(){if(!boxDrag)return;boxDrag=null;changed();renderBlocks();drawLayout()}$('#blockHandles').addEventListener('pointerup',endDrag);$('#blockHandles').addEventListener('pointercancel',endDrag);
$('#blockHandles').addEventListener('keydown',e=>{const t=e.target.closest('[data-handle]');if(!t||!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();const b=currentBoxes()[Number(t.dataset.handle)],step=e.shiftKey?5:1;b.x=Math.max(0,Math.min(100-b.w,b.x+(e.key==='ArrowRight'?step:e.key==='ArrowLeft'?-step:0)));b.y=Math.max(0,Math.min(100-b.h,b.y+(e.key==='ArrowDown'?step:e.key==='ArrowUp'?-step:0)));changed();renderBlocks();drawLayout()});
// Immutable recordings: no commands, no live message insertion, no audio API.
function localDate(ms){return new Date(ms-new Date(ms).getTimezoneOffset()*60000).toISOString().slice(0,16)}
async function loadRecordings(){const d=await api('recordings');$('#recordings').innerHTML=d.recordings.map(r=>`<div class="record"><strong>${esc(r.name)}</strong><p>${esc(new Date(r.at*1000).toLocaleString('nl-NL'))}</p><button data-open-recording="${esc(r.id)}">Open opname</button></div>`).join('')||'<p>Nog geen opnamen bewaard.</p>'}
bind('#capture',async()=>{await api('capture',{name:$('#recordName').value,since:new Date($('#recordFrom').value).getTime()/1000,until:new Date($('#recordUntil').value).getTime()/1000});await loadRecordings();notice('Opname bewaard, inclusief instellingen en ontvangen schermbeslissingen.')});
$('#recordings').addEventListener('click',async e=>{const b=e.target.closest('[data-open-recording]');if(!b)return;try{pause();recording=(await api('recordings?id='+encodeURIComponent(b.dataset.openRecording))).recordings;for(const row of recording.records)row.design=recording.designs?.[row.design_id]||row.design;playIndex=0;$('#player').hidden=false;$('#seek').max=Math.max(0,recording.records.length-1);showFrame()}catch(err){notice(err.message,true)}});
function pause(){clearTimeout(playTimer);playTimer=null;$('#play').textContent='Afspelen'}
function showFrame(){if(!recording?.records?.length)return;playIndex=Math.min(recording.records.length-1,Math.max(0,playIndex));$('#seek').value=playIndex;const row=recording.records[playIndex],saved=row.design?.studio?.config||draft,conf=$('#replayDesign').value==='draft'?draft:saved,s=row.design?.settings||{},m=row.message.corrected||row.message,geo=row.decisions.find(d=>d.geo)?.geo,now=row.at*1000,d=E.decision(conf,m,geo,s,now);let reason=d.reason,show=d.show;
 if(!row.scope){show=false;reason='Bronfilter wees de melding af'}
 const age=now-Date.parse(m.published);if(Number.isFinite(age)&&age>Math.max(1,Number(s.maxAgeMinutes)||5)*60000){show=false;reason='Te oud voor het live scherm'}
 const actual=row.decisions[0];$('#replayInfo').textContent=`${playIndex+1} / ${recording.records.length} · ${new Date(now).toLocaleString('nl-NL')} · ${m.title}`;
 const layout=conf.layout?.enabled?conf.layout:{min_font:24,scenes:{idle:[{type:'clock',x:5,y:20,w:90,h:60}],single:[{type:'message',x:3,y:4,w:94,h:88}],multiple:[]}};
 const [w,h]=(conf.layout?.aspect||'16:9').split(':').map(Number);$('#replayCanvas').height=Math.round(1920*h/w);E.draw($('#replayCanvas'),layout,{message:show?m:null,messages:show?[m]:[],now,preview:true});$('#replayDecision').innerHTML=explain({...d,show,reason})+`<p>Destijds op het scherm: ${esc(actual?actual.client_id+' · '+actual.reason:'geen beslissing ontvangen')}.</p><p class="muted">De simulatie berekent de bron-, profiel-, gebieds- en ouderdomscontrole per melding. Destijds geregistreerde duplicaat-, opstart- en vastzetbeslissingen staan hierboven. Kaarttegels, geluid en de volledige carrousel worden niet opnieuw afgespeeld.</p>`;
}
function play(){pause();if(!recording)return;$('#play').textContent='Speelt…';showFrame();if(playIndex>=recording.records.length-1){pause();return}const wait=Math.max(40,(recording.records[playIndex+1].at-recording.records[playIndex].at)*1000/Number($('#speed').value));playTimer=setTimeout(()=>{playIndex++;play()},Math.min(wait,2147483647))}
bind('#play',play);bind('#pause',pause);bind('#next',()=>{pause();playIndex++;showFrame()});$('#seek').addEventListener('input',e=>{pause();playIndex=Number(e.target.value);showFrame()});$('#replayDesign').addEventListener('change',showFrame);$('#speed').addEventListener('change',()=>{if(playTimer)play()});document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();window.speechSynthesis?.cancel()}});
window.addEventListener('resize',()=>{if(currentTab==='areas')drawMap();if(currentTab==='layout')drawLayout()});
try{const identity=await window.P2000Auth.ready;if(identity.role==='viewer'){document.querySelector('main').innerHTML='<h1>Bedienrechten nodig</h1><p>Dit apparaat heeft kijkrechten. Vraag op de lichtkrant-pc een koppeling met bedienrechten aan.</p>';$('#save').disabled=true;return}design=await api('config');draft=clone(design.config);try{const local=JSON.parse(sessionStorage.getItem('p2000StudioDraft')||'null');if(local&&local.revision===design.revision){draft=local.config;dirty=true;notice('Je nog niet toegepaste ontwerp is hersteld.')}}catch{}settings=(await api('/api/settings')).settings||{};$('#saveState').textContent=dirty?'Nog niet toegepast':'Opgeslagen · versie '+design.revision;$('#recordFrom').value=localDate(Date.now()-3600000);$('#recordUntil').value=localDate(Date.now()+60000);render();chooseTab(['areas','rules','log','speech','corrections','layout','replay'].includes(location.hash.slice(1))?location.hash.slice(1):'areas');await loadLog()}catch(e){notice('Studio laden mislukt: '+e.message,true);$('#save').disabled=true}
})();
