const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require('jsdom');
const E=require('../frontend/studio-engine.js');
const rule=(id,when,action='show')=>({id,name:id,when,action,enabled:true});
const config=rules=>({enabled:true,default_action:'hide',unknown_location:'show',rules,zones:[{id:'town',enabled:true,points:[[51,4],[52,4],[52,6],[51,6]]}]});
const m={service:'ambulance',priority:'A1',city:'Tilburg',location:'Teststraat',title:'A1 Teststraat Tilburg',units:[]};
test('Polygon includes boundaries and rejects outside points',()=>{const p=config([]).zones[0].points;assert.equal(E.inside({lat:51.5,lon:5},p),true);assert.equal(E.inside({lat:51,lon:5},p),true);assert.equal(E.inside({lat:53,lon:5},p),false);assert.equal(E.inside(null,p),null)});
test('First matching exception wins and every condition must match',()=>{const c=config([rule('OvDG',{resource:'ovdg'}),rule('Geen ambulance',{service:'ambulance'},'hide')]);assert.equal(E.evaluate(c,{...m,title:'A1 OvD-G 803 Tilburg'}).show,true);assert.equal(E.evaluate(c,m).show,false);assert.equal(E.evaluate(config([rule('Allebei',{service:'brandweer',city:'Tilburg'})]),m).show,false)});
test('Unknown and expired areas are explicit and deterministic',()=>{const c=config([rule('gebied',{zone:'town'},'hide'),rule('rest',{})]);assert.equal(E.evaluate(c,m).unknown,true);assert.equal(E.evaluate(c,m).show,true);c.unknown_location='hide';assert.equal(E.evaluate(c,m).show,false);c.zones[0].expires=100;assert.equal(E.evaluate(c,m,{lat:51.5,lon:5},101).rule,'rest')});
test('Area lookup is unnecessary for a service-mismatched rule',()=>{const c=config([rule('Brandweer',{zone:'town',service:'brandweer'}),rule('Ambulance',{service:'ambulance'})]);assert.equal(E.evaluate(c,m).unknown,undefined);assert.equal(E.evaluate(c,m).rule,'Ambulance')});
test('Native scale scores distinguish middel and grote brand',()=>{const c=config([rule('Groot',{min_scale:60})]);assert.equal(E.evaluate(c,{...m,scale_score:50}).show,false);assert.equal(E.evaluate(c,{...m,scale_score:60}).show,true)});
test('Rules replace legacy city filter while exercise profile remains authoritative',()=>{const c=config([rule('Binnen',{city:'Tilburg'})]);assert.equal(E.decision(c,m,null,{cities:['Eemnes']}).show,true);assert.equal(E.decision(c,m,null,{exerciseMode:true}).show,false);assert.equal(E.decision({...c,enabled:false},m,null,{cities:['Eemnes']}).show,false)});
test('Silent and urgent rules do not invent sound permissions',()=>{assert.equal(E.evaluate(config([rule('Stil',{},'silent')]),m).speak,false);const d=E.evaluate(config([rule('Snel',{},'urgent')]),m);assert.equal(d.urgent,true);assert.equal(d.show,true)});
test('Template removes missing sections and retains literal user text',()=>{assert.equal(E.phrase('{incident}{where}. {scale} {units}',{incident:'Brand',where:' in Tilburg'}),'Brand in Tilburg.');assert.equal(E.phrase('Let op: {priority}.',{priority:'P1'}),'Let op: P1.')});
const read=name=>fs.readFileSync(path.join(__dirname,'../frontend',name),'utf8');
function screen(preview=false){const dom=new JSDOM(read('index.html'),{url:'http://127.0.0.1:8765/',runScripts:'outside-only'}),w=dom.window;w.P2000_STUDIO_PREVIEW=preview;w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({measureText:t=>({width:String(t).length*10}),createLinearGradient:()=>({addColorStop(){}})}, {get:(o,k)=>o[k]||(()=>{})});w.requestAnimationFrame=()=>1;w.matchMedia=()=>({matches:false});w.eval(read('studio-engine.js'));w.eval(read('studio-live.js'));return {dom,w}}
test('Preview frame loads the entire app without fetching or starting live timers',()=>{const {dom,w}=screen(true);let calls=0;w.fetch=()=>{calls++;throw new Error('No network in inert preview')};w.setInterval=()=>{calls++;return 1};try{w.eval(read('app.js'));assert.equal(calls,0);assert.equal(typeof w.P2000SpeechPreview.format,'function');const conf=config([]);conf.speech={enabled:true,template:'Prioriteit {priority}. {city}.',cue:false};const text=w.P2000SpeechPreview.format({...m,title:'A1 Teststraat Tilburg'}, {revision:1,config:conf},{});assert.equal(text,'Prioriteit A1. Tilburg.');assert.equal(calls,0)}finally{dom.window.close()}});
test('Live filter applies studio rules and logs hidden incoming messages',()=>{const {dom,w}=screen();try{const src=read('app.js').split('let controlsTimer=null;')[0];w.eval(src+`\nwindow.stateForTest=state;window.filterTest=filterMessage;window.processTest=processNew;window.setStudioJson=fn=>{json=fn};`);w.stateForTest.bootAt=Date.now()-10000;const posts=[];w.setStudioJson(async(url,opts)=>{if(opts)posts.push(JSON.parse(opts.body));return {ok:true}});w.P2000StudioLive.apply({revision:1,config:config([rule('Verberg ambulance',{service:'ambulance'},'hide')])});assert.equal(w.filterTest(m),false);w.processTest({...m,id:'new',published:new Date().toISOString(),ingested_at:new Date().toISOString()});assert.equal(posts.length,1);assert.equal(posts[0].shown,false);assert.match(posts[0].reason,/Verberg ambulance/)}finally{dom.window.close()}});
test('Corrected vehicle list does not resurrect callsigns from the original text',()=>{const {dom,w}=screen();try{w.eval(read('app.js').split('let controlsTimer=null;')[0]+`\nwindow.details=vehicleDetails;`);const details=w.details({title:'P 1 BR Woning Teststraat Tilburg 20-9432',service:'brandweer',priority:'P1',city:'Tilburg',units:[],parser_notes:['Lokale voertuigcorrectie']});assert.equal(details.length,0)}finally{dom.window.close()}});
test('Shared scene renderer selects layouts and reports text pagination',()=>{const {dom,w}=screen();try{const canvas=w.document.querySelector('canvas');canvas.width=1920;canvas.height=1080;const box={type:'message',x:0,y:0,w:10,h:10};const layout={min_font:40,scenes:{idle:[],single:[box],multiple:[]}};assert.equal(E.scene(layout,1)[0],box);assert.equal(E.scene(layout,2).length,0);assert.ok(E.draw(canvas,layout,{message:{title:'Lang bericht '.repeat(100)},messages:[m],preview:true}).length)}finally{dom.window.close()}});
// Execute the real editor with mocked HTTP, not a mirror of its event handlers.
async function editor(){const dom=new JSDOM(read('studio.html'),{url:'http://127.0.0.1:8765/studio.html',runScripts:'outside-only'}),w=dom.window,requests=[];w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({measureText:t=>({width:String(t).length*8})},{get:(o,k)=>o[k]||(()=>{})});w.P2000Auth={ready:Promise.resolve({role:'controller'})};w.scrollTo=()=>{};const cfg={...config([]),speech:{enabled:false,template:'{incident}{where}. {units}',cue:true},layout:{enabled:false,aspect:'16:9',min_font:24,scenes:{idle:[],single:[],multiple:[]}},corrections:[],examples:[]};w.fetch=async(url,opts)=>{requests.push({url,opts});let body=url.includes('/config')?{ok:true,revision:0,config:cfg}:url==='/api/settings'?{settings:{}}:url.includes('/recordings')?{ok:true,recordings:[]}:url.includes('/records')?{ok:true,records:[]}:url.includes('/validate')?{ok:true,config:JSON.parse(opts.body).config}:{ok:true};return {ok:true,json:async()=>body}};w.eval(read('studio-engine.js'));await w.eval(read('studio.js'));return{dom,w,requests}}
test('Studio navigation and rule edit survive a real save',async()=>{const {dom,w,requests}=await editor();try{w.document.querySelector('[data-tab="rules"]').click();assert.equal(w.document.querySelector('#rules').hidden,false);w.document.querySelector('#addRule').click();const field=w.document.querySelector('[data-key="name"]');field.value='Alleen Tilburg';field.dispatchEvent(new w.Event('change',{bubbles:true}));w.document.querySelector('#save').click();await new Promise(r=>setTimeout(r,25));const saved=requests.find(x=>x.url.endsWith('/config')&&x.opts?.method==='POST');assert.ok(saved);assert.equal(JSON.parse(saved.opts.body).config.rules[0].name,'Alleen Tilburg')}finally{dom.window.close()}});
test('Opening studio never sends a test, replay or audio command',async()=>{const {dom,requests}=await editor();try{assert.equal(requests.filter(x=>x.opts?.method==='POST').length,0);assert.equal(requests.some(x=>/tts|quick-action|message-action/.test(x.url)),false)}finally{dom.window.close()}});

test('Live custom scene renders through the integration adapter',()=>{const {dom,w}=screen();try{w.eval(read('app.js').split('let controlsTimer=null;')[0]);const c=config([]);c.layout={enabled:true,min_font:24,scenes:{idle:[{type:'clock',x:0,y:0,w:100,h:100}],single:[],multiple:[]}};w.P2000StudioLive.apply({revision:1,config:c});assert.equal(w.P2000StudioLive.drawCustom(),true);assert.equal(w.P2000StudioLive.mapBox(),null)}finally{dom.window.close()}});
