'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let step=1,setup=null,regions=[],disciplines=[],githubSettings={};
const labels={brandweer:'Brandweer',ambulance:'Ambulance',politie:'Politie',knrm:'KNRM',lifeliner:'Lifeliner'};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function api(url,opt){const ctrl=new AbortController(),timer=setTimeout(()=>ctrl.abort(),12000);try{const r=await fetch(url,{cache:'no-store',signal:ctrl.signal,...(opt||{})});const text=await r.text();let d={};try{d=text?JSON.parse(text):{}}catch{}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}catch(e){if(e?.name==='AbortError')throw new Error('Backend reageert niet binnen 12 seconden');throw e}finally{clearTimeout(timer)}}
function profileType(){return $('input[name="profileType"]:checked')?.value||'particulier'}
function toggleProfile(){const company=profileType()==='bedrijf';$('#privateFields').hidden=company;$('#companyFields').hidden=!company}
function matrix(){const out={};$$('#regionRows tr[data-region]').forEach(tr=>{const vals=qsa('input[data-disc]',tr).filter(x=>x.checked).map(x=>x.dataset.disc);if(vals.length)out[tr.dataset.region]=vals});return out}
function qsa(sel,root=document){return [...root.querySelectorAll(sel)]}
function feedUrls(m){
  const urls=[],special=new Set(),safety=regions.filter(r=>r.kind==='veiligheidsregio').map(r=>r.slug),parents={achterhoek:'noord-en-oost-gelderland',bollenstreek:'hollands-midden','hoeksche-waard':'zuid-holland-zuid'};
  for(const d of ['brandweer','ambulance','politie']){
    const selectedSafety=safety.filter(slug=>(m[slug]||[]).includes(d));
    if(safety.length&&selectedSafety.length===safety.length){urls.push(`https://alarmeringen.nl/feeds/discipline/${d}.rss`);continue}
    for(const [region,ds] of Object.entries(m)){
      if(!ds.includes(d))continue;
      const parent=parents[region];if(parent&&(m[parent]||[]).includes(d))continue;
      urls.push(`https://alarmeringen.nl/feeds/region/${region}/${d}.rss`)
    }
  }
  for(const ds of Object.values(m)){if(ds.includes('knrm'))special.add('https://alarmeringen.nl/feeds/discipline/knrm.rss');if(ds.includes('lifeliner'))special.add('https://alarmeringen.nl/feeds/discipline/trauma.rss')}
  return [...new Set([...urls,...special])]
}
function renderRows(){const existing=setup?.region_disciplines||{};$('#regionRows').innerHTML=regions.map(r=>{const set=new Set(existing[r.slug]||[]);return `<tr data-region="${esc(r.slug)}"><td><div class="region-name"><b>${esc(r.label)}</b>${r.kind==='subregio'?'<small>SUBREGIO</small>':''}</div></td>${['brandweer','ambulance','politie','knrm','lifeliner'].map(d=>`<td><input type="checkbox" data-disc="${d}" aria-label="${esc(r.label)} ${labels[d]}" ${set.has(d)?'checked':''}></td>`).join('')}<td><input type="checkbox" data-all aria-label="Alles voor ${esc(r.label)}"></td></tr>`}).join('');qsa('#regionRows input').forEach(x=>x.addEventListener('change',onMatrixChange));updateMatrix()}
function onMatrixChange(e){const tr=e.target.closest('tr');if(e.target.matches('[data-all]'))qsa('[data-disc]',tr).forEach(x=>x.checked=e.target.checked);updateMatrix()}
function updateMatrix(){let count=0;qsa('#regionRows tr').forEach(tr=>{const checks=qsa('[data-disc]',tr),n=checks.filter(x=>x.checked).length;count+=n;tr.classList.toggle('selected',n>0);const all=tr.querySelector('[data-all]');all.checked=n===checks.length;all.indeterminate=n>0&&n<checks.length});$('#selectionCounter').textContent=`${count} combinatie${count===1?'':'s'}`;const urls=feedUrls(matrix());$('#feedPreview').innerHTML=urls.length?urls.map(u=>`<div>${esc(u)}</div>`).join(''):'Selecteer eerst een combinatie.';renderSummary()}
function filterRegions(){const q=$('#regionSearch').value.trim().toLowerCase();qsa('#regionRows tr').forEach(tr=>{const name=tr.textContent.toLowerCase();tr.hidden=!!q&&!name.includes(q)})}
function preset(kind){const visible=qsa('#regionRows tr').filter(tr=>!tr.hidden),safetySet=new Set(regions.filter(r=>r.kind==='veiligheidsregio').map(r=>r.slug));if(kind==='clear'){qsa('#regionRows [data-disc]').forEach(x=>x.checked=false)}else if(kind==='basic'){visible.forEach(tr=>qsa('[data-disc]',tr).forEach(x=>x.checked=['brandweer','politie','lifeliner'].includes(x.dataset.disc)))}else if(['nl-brw-pol','nl-brw','nl-pol'].includes(kind)){qsa('#regionRows tr').forEach(tr=>{const isSafety=safetySet.has(tr.dataset.region);qsa('[data-disc]',tr).forEach(x=>{if(kind==='nl-brw-pol')x.checked=isSafety&&['brandweer','politie'].includes(x.dataset.disc);else if(kind==='nl-brw')x.checked=isSafety&&x.dataset.disc==='brandweer';else x.checked=isSafety&&x.dataset.disc==='politie'})})}else if(kind==='all-services'){visible.forEach(tr=>qsa('[data-disc]',tr).forEach(x=>x.checked=true))}updateMatrix()}
function suggestName(){if($('#monitorName').dataset.touched==='1')return;const place=$('#standplaats').value.trim();$('#monitorName').value=place?`P2000 ${place}`:'P2000 Monitor'}
function validateStep(n){hideError();if(n===1){if(profileType()==='particulier'&&!$('#personName').value.trim())return error('Vul je naam in.');if(profileType()==='bedrijf'&&!$('#companyName').value.trim())return error('Vul de bedrijfs- of organisatienaam in.')}if(n===2&&!$('#standplaats').value.trim())return error('Vul een standplaats of hoofdplaats in.');if(n===3&&!Object.keys(matrix()).length)return error('Selecteer minimaal één regio en discipline.');return true}
function error(msg){const e=$('#formError');e.textContent=msg;e.hidden=false;e.scrollIntoView({behavior:'smooth',block:'nearest'});return false}function hideError(){$('#formError').hidden=true}
function showStep(n){step=Math.max(1,Math.min(4,n));qsa('.step-panel').forEach(x=>x.classList.toggle('active',Number(x.dataset.step)===step));qsa('[data-step-jump]').forEach(x=>{const k=Number(x.dataset.stepJump);x.classList.toggle('active',k===step);x.classList.toggle('done',k<step)});$('#backBtn').disabled=step===1;$('#nextBtn').hidden=step===4;$('#saveSetupBtn').hidden=step!==4;if(step===4)renderSummary();window.scrollTo({top:0,behavior:'smooth'})}
function renderSummary(){if(!$('#summaryCards'))return;const m=matrix(),selected=Object.entries(m),combos=selected.reduce((n,[,d])=>n+d.length,0),feeds=feedUrls(m);const company=profileType()==='bedrijf',who=company?($('#companyName').value.trim()||'—'):($('#personName').value.trim()||'—');const resolvedCity=String(setup?.standplaats_city||'').trim();const ownerExtra=company?[($('#departmentName').value.trim()||''),($('#contactName').value.trim()?`Contact: ${$('#contactName').value.trim()}`:'')].filter(Boolean).join(' • '):'Particulier';const ds=[...new Set(selected.flatMap(([,d])=>d))].map(x=>labels[x]).join(', ')||'—';$('#summaryCards').innerHTML=`<div class="summary-card"><span>Gebruiker</span><b>${esc(who)}</b><small>${esc(ownerExtra||'Bedrijf / organisatie')}</small></div><div class="summary-card"><span>Standplaats</span><b>${esc($('#standplaats').value.trim()||'—')}</b><small>${esc((resolvedCity&&resolvedCity!==$('#standplaats').value.trim()?`Plaats: ${resolvedCity} • `:'')+($('#monitorName').value.trim()||'P2000 Monitor'))}</small></div><div class="summary-card"><span>Regio's</span><b>${selected.length}</b><small>${esc(selected.map(([slug])=>regions.find(r=>r.slug===slug)?.label||slug).join(', ')||'Geen')}</small></div><div class="summary-card"><span>Ontvangst</span><b>${combos} combinaties</b><small>${esc(ds)} • ${feeds.length} RSS-bronnen</small></div>`}
async function checkLocation(){const place=$('#standplaats').value.trim(),b=$('#checkLocationBtn'),out=$('#locationCheckResult');if(!place)return error('Vul eerst een standplaats in.');b.disabled=true;out.className='check-result';out.textContent='PDOK controleren…';try{const d=await api(`/api/geocode?city=${encodeURIComponent(place)}`);const m=d.map||{};out.className='check-result ok';out.textContent=`Gevonden: ${m.display_name||place}${m.source?' • '+m.source:''}`;}catch(e){out.className='check-result bad';out.textContent=`Niet bevestigd: ${e.message}. Je kunt de plaats alsnog gebruiken en later aanpassen.`}finally{b.disabled=false}}
async function save(e){e.preventDefault();if(![1,2,3].every(validateStep))return;const payload={profile_type:profileType(),person_name:$('#personName').value.trim(),company_name:$('#companyName').value.trim(),department_name:$('#departmentName').value.trim(),contact_name:$('#contactName').value.trim(),standplaats:$('#standplaats').value.trim(),monitor_name:$('#monitorName').value.trim(),region_disciplines:matrix(),poll_interval_seconds:Number($('#pollInterval').value)||8};const b=$('#saveSetupBtn');b.disabled=true;b.textContent='Opslaan…';try{await api('/api/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const repo=$('#githubRepo').value.trim();await api('/api/update/github/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({github_repo:repo,github_auto_check:!!repo,github_auto_install:!!repo&&$('#githubAutoInstall').checked,github_check_minutes:Number($('#githubCheckMinutes').value)||5})}).catch(err=>{console.warn('GitHub-updateinstellingen konden niet worden opgeslagen:',err)});b.textContent='Opgeslagen ✓';setTimeout(()=>location.replace('/'),450)}catch(err){error(`Opslaan mislukt: ${err.message}`);b.disabled=false;b.textContent='Opslaan en monitor starten'}}
async function init(){try{const [d,u]=await Promise.all([api('/api/setup'),api('/api/update/github/settings').catch(()=>({settings:{}}))]);setup=d.setup||{};githubSettings=u.settings||{};regions=setup.regions||[];disciplines=setup.disciplines||[];const p=setup.profile_type||'particulier';const radio=$(`input[name="profileType"][value="${p}"]`);if(radio)radio.checked=true;$('#personName').value=setup.person_name||'';$('#companyName').value=setup.company_name||'';$('#departmentName').value=setup.department_name||'';$('#contactName').value=setup.contact_name||'';$('#standplaats').value=setup.standplaats||'';$('#monitorName').value=setup.monitor_name||'';$('#pollInterval').value=String(setup.poll_interval_seconds||8);if(!$('#pollInterval').value)$('#pollInterval').value='8';$('#githubRepo').value=githubSettings.github_repo||'xSophie1119/lichtkrant';$('#githubCheckMinutes').value=String(githubSettings.github_check_minutes||5);$('#githubAutoInstall').checked=!!githubSettings.github_auto_install;if(setup.monitor_name)$('#monitorName').dataset.touched='1';toggleProfile();renderRows();renderSummary()}catch(e){error(`Wizard kon configuratie niet laden: ${e.message}`)}}
qsa('input[name="profileType"]').forEach(x=>x.addEventListener('change',()=>{toggleProfile();renderSummary()}));$('#standplaats').addEventListener('input',()=>{suggestName();renderSummary()});$('#monitorName').addEventListener('input',()=>{$('#monitorName').dataset.touched='1';renderSummary()});['personName','companyName','departmentName','contactName'].forEach(id=>$('#'+id).addEventListener('input',renderSummary));$('#regionSearch').addEventListener('input',filterRegions);qsa('[data-preset]').forEach(b=>b.addEventListener('click',()=>preset(b.dataset.preset)));$('#checkLocationBtn').addEventListener('click',checkLocation);$('#backBtn').addEventListener('click',()=>showStep(step-1));$('#nextBtn').addEventListener('click',()=>{if(validateStep(step))showStep(step+1)});qsa('[data-step-jump]').forEach(b=>b.addEventListener('click',()=>{const target=Number(b.dataset.stepJump);if(target<step||[1,2,3].slice(0,target-1).every(validateStep))showStep(target)}));$('#setupForm').addEventListener('submit',save);init();

window.addEventListener('unhandledrejection',e=>{try{error(`Wizardfout: ${e.reason?.message||e.reason||'onbekende fout'}`)}catch{}});
window.addEventListener('error',e=>{try{error(`Wizardfout: ${e.message||'onbekende JavaScript-fout'}`)}catch{}});
